//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SIGEES.Entidades
{
    public  class cliente_dto
    {
        public cliente_dto()
        {
            this.reserva = new HashSet<reserva_dto>();
            this.venta = new HashSet<venta_dto>();
        }

        public string codigo_cliente { get; set; }
        public int codigo_persona { get; set; }
        public string estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }

        public virtual ICollection<reserva_dto> reserva { get; set; }
        public virtual ICollection<venta_dto> venta { get; set; }
        public virtual persona_dto persona { get; set; }
    }
}