//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_estado_espacio_dto
    {
        public int codigo_det_estado_espcio { get; set; }
        public string codigo_espacio { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public int codigo_estado_espacio { get; set; }

        //public int codigo_tipo_tabla { set; get; }
        //public int codigo_tabla { set; get; }

        //public virtual espacio_dto espacio { get; set; }
        //public virtual estado_espacio_dto estado_espacio { get; set; }
    }
}
