//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SIGEES.Entidades
{
    [Serializable]
    public  class espacio_dto
    {



        public espacio_dto() {
            campo_santo = new campo_santo_dto();
            corporacion = new corporacion_dto();
            empresa = new empresa_dto();
            plataforma = new plataforma_dto();
            estado_espacio = new estado_espacio_dto();
            tipo_espacio_dto = new tipo_espacio_dto();
            producto = new producto_dto();
            sector = new sector_dto();
        }

        public virtual sector_dto sector { set; get; }
        public int posicion_x { set; get; }
        public int posicion_y { set; get; }

        public string codigo_espacio { get; set; }
        public int codigo_corporacion { get; set; }
        public int codigo_empresa { get; set; }
        public int codigo_campo_santo { get; set; }
        public int codigo_plataforma { get; set; }
        public int tipo_espacio { get; set; }
        public string codigo_tipo_nivel { get; set; }
        public string eje_derecho { get; set; }
        public string eje_izquierdo { get; set; }
        public string je_superior { get; set; }
        public string eje_inferior { get; set; }
        public string eje_superior { get; set; }

        public string codigo_plano { get; set; }
        public string numero_lote { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }

        public virtual campo_santo_dto campo_santo { get; set; }
        public virtual corporacion_dto corporacion { get; set; }
        public virtual ICollection<detalle_producto_dto> detalle_producto { get; set; }
        public virtual empresa_dto empresa { get; set; }
        public virtual ICollection<lote_dto> lote { get; set; }
        public virtual ICollection<nicho_dto> nicho { get; set; }
        public virtual ICollection<registro_fallecido_dto> registro_fallecido { get; set; }
        public virtual plataforma_dto plataforma { get; set; }
        public virtual tipo_espacio_dto tipo_espacio1 { get; set; }
        public virtual tipo_nivel_dto tipo_nivel { get; set; }
        public virtual estado_espacio_dto estado_espacio { get; set; }
        public virtual producto_dto producto { get; set; }
        public virtual tipo_espacio_dto tipo_espacio_dto { get; set; }  
        
        public string eje_columna { get; set; }
        public int eje_fila { get; set; }
        public string codigo_sector { get; set; }

        public int orden_ubicacion { get; set; }
        //public int cantidad_reserva_por_vendedor { get; set; }

        public DateTime? fecha_ultimo_entierro { get; set; }
        public bool habilitado { get; set; }
        public int numero_secuencia_sector { get; set; }

        public int cantidad_maxima_conversion { get; set; }

        public string numero_grupo { get; set;}
        public string codigo_espacio_visual { get; set; }
    }
}