//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_espacio_dto
    {
        public estado_espacio_dto()
        {
            this.detalle_estado_espacio_dto = new HashSet<detalle_estado_espacio_dto>();
        }

    
        public int codigo_estado_espacio { get; set; }
        public string nombre_estado_espacio { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_registra { get; set; }
        public int codigo_espacio { get; set; }
    
        /// <summary>
        /// detalle del estado
        /// </summary>
        public virtual ICollection<detalle_estado_espacio_dto> detalle_estado_espacio_dto { get; set; }
    }
}
