//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SIGEES.Entidades
{
    public class plataforma_dto
    {
        //public plataforma_dto()
        //{
        //    this.espacio = new HashSet<espacio_dto>();
        //}

        public int numero_sector { get; set; }
        public int codigo_plataforma { get; set; }
        public int codigo_corporacion { get; set; }
        public int codigo_empresa { get; set; }
        public int codigo_campo_santo { get; set; }
        public string nombre_plataforma { get; set; }
        public string nombre_empresa { get; set; }
        public string nombre_camposanto { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }

        public string fecha_registra_cadena { get; set; }
        public string fecha_modifica_cadena { get; set; }

        //public virtual campo_santo_dto campo_santo { get; set; }
        //public virtual corporacion_dto corporacion { get; set; }
        //public virtual empresa_dto empresa { get; set; }
        public List<espacio_dto> espacios { get; set; }

        public int numero_columnas { get; set; }
        public string identificador { get; set; }
        public int codigo_tipo_plataforma { get; set; }
        public int? cantidad_pisos_sector { get; set; }

        public int numero_filas { get; set; }
        public int cantidad_espacios { get; set; }
        public int espacios_ocupados { get; set; }
        public int espacios_libre { get; set; }

        public int espacios_vendidos { get; set; }
        public int espacios_reservados { get; set; }

        public string extends_asignar { set; get; }
        public string extends_liberar { set; get; }
        public int cantidad_maxima_conversion { get; set; }
        public int? codigo_tipo_espacio { get; set; }
    }
}