//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SIGEES.Entidades
{
    public  class registro_incinerado_dto
    {
        public int codigo_registro_incinerado { get; set; }
        public int codigo_fallecido { get; set; }
        public int codigo_registro_fallecido { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }

        public virtual fallecido_dto fallecido { get; set; }
        public virtual registro_fallecido_dto registro_fallecido { get; set; }
    }
}