//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SIGEES.Entidades
{  [Serializable]
    public  class reserva_dto
    {
        public reserva_dto()
        {
            espacio = new espacio_dto();
            plataforma = new plataforma_dto();
            empresa = new empresa_dto();
            campo_santo = new campo_santo_dto();
            corporacion = new corporacion_dto();
            vendedor = new persona_dto();
            cliente = new persona_dto();
            det_estado_espacio = new detalle_estado_espacio_dto();
            //this.venta = new HashSet<venta_dto>();
        }


        public int ind_operacion { get; set; }
        public int codigo_reserva { get; set; }
        public string codigo_espacio { set; get; }
        public string memo_reserva { get; set; }
        public string fecha_reserva { get; set; }
        public string codigo_cliente { get; set; }
        public string codigo_usuario { get; set; }
        public int codigo_producto { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }

        //public virtual cliente cliente { get; set; }

        public virtual detalle_estado_espacio_dto det_estado_espacio { set; get; }
        public virtual espacio_dto espacio { get; set; }
        public virtual plataforma_dto plataforma { get; set; }
        public virtual empresa_dto empresa { get; set; }
        public virtual producto_dto producto { get; set; }
        public virtual campo_santo_dto campo_santo { get; set; }
        public virtual corporacion_dto corporacion { get; set; }

        public virtual persona_dto vendedor { set; get; }
        public virtual persona_dto cliente { set; get; }
       // public virtual ICollection<venta_dto> venta { get; set; }
        //public virtual usuario usuario { get; set; }

        public DateTime? fecha_caducidad { get; set; }

        public string numero_documento_cliente { get; set; }
        public string ape_paterno_cliente { get; set; }
        public string ape_materno_cliente { get; set; }
        public string nombre_cliente { get; set; }

        public string codigo_autorizacion { get; set; }
    
    }
}