//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SIGEES.Entidades
{
    public  class tipo_fallecido_dto
    {
        public tipo_fallecido_dto()
        {
            this.fallecido = new HashSet<fallecido_dto>();
        }

        public int codigo_tipo_fallecido { get; set; }
        public string nombre_tipo_fallecido { get; set; }
        public bool estado_registra { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }

        public virtual ICollection<fallecido_dto> fallecido { get; set; }
    }
}