//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SIGEES.Web.Areas.Comision.Reporte.PlanillaBono.ds {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsLiquidacionBonoSupervisorIndividual")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsLiquidacionBonoSupervisorIndividual : global::System.Data.DataSet {
        
        private dt_liquidacion_bono_supervisor_individualDataTable tabledt_liquidacion_bono_supervisor_individual;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsLiquidacionBonoSupervisorIndividual() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsLiquidacionBonoSupervisorIndividual(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dt_liquidacion_bono_supervisor_individual"] != null)) {
                    base.Tables.Add(new dt_liquidacion_bono_supervisor_individualDataTable(ds.Tables["dt_liquidacion_bono_supervisor_individual"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dt_liquidacion_bono_supervisor_individualDataTable dt_liquidacion_bono_supervisor_individual {
            get {
                return this.tabledt_liquidacion_bono_supervisor_individual;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsLiquidacionBonoSupervisorIndividual cln = ((dsLiquidacionBonoSupervisorIndividual)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dt_liquidacion_bono_supervisor_individual"] != null)) {
                    base.Tables.Add(new dt_liquidacion_bono_supervisor_individualDataTable(ds.Tables["dt_liquidacion_bono_supervisor_individual"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledt_liquidacion_bono_supervisor_individual = ((dt_liquidacion_bono_supervisor_individualDataTable)(base.Tables["dt_liquidacion_bono_supervisor_individual"]));
            if ((initTable == true)) {
                if ((this.tabledt_liquidacion_bono_supervisor_individual != null)) {
                    this.tabledt_liquidacion_bono_supervisor_individual.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsLiquidacionBonoSupervisorIndividual";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsLiquidacionBonoSupervisorIndividual.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledt_liquidacion_bono_supervisor_individual = new dt_liquidacion_bono_supervisor_individualDataTable();
            base.Tables.Add(this.tabledt_liquidacion_bono_supervisor_individual);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializedt_liquidacion_bono_supervisor_individual() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsLiquidacionBonoSupervisorIndividual ds = new dsLiquidacionBonoSupervisorIndividual();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dt_liquidacion_bono_supervisor_individualRowChangeEventHandler(object sender, dt_liquidacion_bono_supervisor_individualRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dt_liquidacion_bono_supervisor_individualDataTable : global::System.Data.TypedTableBase<dt_liquidacion_bono_supervisor_individualRow> {
            
            private global::System.Data.DataColumn columncodigo_supervisor;
            
            private global::System.Data.DataColumn columncodigo_empresa;
            
            private global::System.Data.DataColumn columnapellidos_nombres_supervisor;
            
            private global::System.Data.DataColumn columnnombre_empresa;
            
            private global::System.Data.DataColumn columnnombre_grupo;
            
            private global::System.Data.DataColumn columnmonto_bruto_empresa_supervisor;
            
            private global::System.Data.DataColumn columnmonto_igv_empresa_supervisor;
            
            private global::System.Data.DataColumn columnmonto_neto_empresa_supervisor;
            
            private global::System.Data.DataColumn columnmonto_detraccion_empresa_supervisor;
            
            private global::System.Data.DataColumn columnnro_documento;
            
            private global::System.Data.DataColumn columnnombre_tipo_documento;
            
            private global::System.Data.DataColumn columnruc;
            
            private global::System.Data.DataColumn columnnombre_empresa_largo;
            
            private global::System.Data.DataColumn columndireccion_fiscal;
            
            private global::System.Data.DataColumn columnconcepto;
            
            private global::System.Data.DataColumn columnporcentaje_detraccion;
            
            private global::System.Data.DataColumn columnfecha_inicio;
            
            private global::System.Data.DataColumn columnfecha_fin;
            
            private global::System.Data.DataColumn columncodigo_estado_planilla;
            
            private global::System.Data.DataColumn columnmonto_neto_pagar_empresa_supervisor;
            
            private global::System.Data.DataColumn columnneto_pagar_empresa_supervisor_letra;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_liquidacion_bono_supervisor_individualDataTable() {
                this.TableName = "dt_liquidacion_bono_supervisor_individual";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dt_liquidacion_bono_supervisor_individualDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dt_liquidacion_bono_supervisor_individualDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_supervisorColumn {
                get {
                    return this.columncodigo_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_empresaColumn {
                get {
                    return this.columncodigo_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn apellidos_nombres_supervisorColumn {
                get {
                    return this.columnapellidos_nombres_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_empresaColumn {
                get {
                    return this.columnnombre_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_grupoColumn {
                get {
                    return this.columnnombre_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_bruto_empresa_supervisorColumn {
                get {
                    return this.columnmonto_bruto_empresa_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_igv_empresa_supervisorColumn {
                get {
                    return this.columnmonto_igv_empresa_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_neto_empresa_supervisorColumn {
                get {
                    return this.columnmonto_neto_empresa_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_detraccion_empresa_supervisorColumn {
                get {
                    return this.columnmonto_detraccion_empresa_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nro_documentoColumn {
                get {
                    return this.columnnro_documento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_tipo_documentoColumn {
                get {
                    return this.columnnombre_tipo_documento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn rucColumn {
                get {
                    return this.columnruc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_empresa_largoColumn {
                get {
                    return this.columnnombre_empresa_largo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn direccion_fiscalColumn {
                get {
                    return this.columndireccion_fiscal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn conceptoColumn {
                get {
                    return this.columnconcepto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn porcentaje_detraccionColumn {
                get {
                    return this.columnporcentaje_detraccion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fecha_inicioColumn {
                get {
                    return this.columnfecha_inicio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fecha_finColumn {
                get {
                    return this.columnfecha_fin;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_estado_planillaColumn {
                get {
                    return this.columncodigo_estado_planilla;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_neto_pagar_empresa_supervisorColumn {
                get {
                    return this.columnmonto_neto_pagar_empresa_supervisor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn neto_pagar_empresa_supervisor_letraColumn {
                get {
                    return this.columnneto_pagar_empresa_supervisor_letra;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_liquidacion_bono_supervisor_individualRow this[int index] {
                get {
                    return ((dt_liquidacion_bono_supervisor_individualRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_liquidacion_bono_supervisor_individualRowChangeEventHandler dt_liquidacion_bono_supervisor_individualRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_liquidacion_bono_supervisor_individualRowChangeEventHandler dt_liquidacion_bono_supervisor_individualRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_liquidacion_bono_supervisor_individualRowChangeEventHandler dt_liquidacion_bono_supervisor_individualRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_liquidacion_bono_supervisor_individualRowChangeEventHandler dt_liquidacion_bono_supervisor_individualRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Adddt_liquidacion_bono_supervisor_individualRow(dt_liquidacion_bono_supervisor_individualRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_liquidacion_bono_supervisor_individualRow Adddt_liquidacion_bono_supervisor_individualRow(
                        string codigo_supervisor, 
                        string codigo_empresa, 
                        string apellidos_nombres_supervisor, 
                        string nombre_empresa, 
                        string nombre_grupo, 
                        decimal monto_bruto_empresa_supervisor, 
                        decimal monto_igv_empresa_supervisor, 
                        decimal monto_neto_empresa_supervisor, 
                        decimal monto_detraccion_empresa_supervisor, 
                        string nro_documento, 
                        string nombre_tipo_documento, 
                        string ruc, 
                        string nombre_empresa_largo, 
                        string direccion_fiscal, 
                        string concepto, 
                        string porcentaje_detraccion, 
                        string fecha_inicio, 
                        string fecha_fin, 
                        string codigo_estado_planilla, 
                        string monto_neto_pagar_empresa_supervisor, 
                        string neto_pagar_empresa_supervisor_letra) {
                dt_liquidacion_bono_supervisor_individualRow rowdt_liquidacion_bono_supervisor_individualRow = ((dt_liquidacion_bono_supervisor_individualRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        codigo_supervisor,
                        codigo_empresa,
                        apellidos_nombres_supervisor,
                        nombre_empresa,
                        nombre_grupo,
                        monto_bruto_empresa_supervisor,
                        monto_igv_empresa_supervisor,
                        monto_neto_empresa_supervisor,
                        monto_detraccion_empresa_supervisor,
                        nro_documento,
                        nombre_tipo_documento,
                        ruc,
                        nombre_empresa_largo,
                        direccion_fiscal,
                        concepto,
                        porcentaje_detraccion,
                        fecha_inicio,
                        fecha_fin,
                        codigo_estado_planilla,
                        monto_neto_pagar_empresa_supervisor,
                        neto_pagar_empresa_supervisor_letra};
                rowdt_liquidacion_bono_supervisor_individualRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdt_liquidacion_bono_supervisor_individualRow);
                return rowdt_liquidacion_bono_supervisor_individualRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dt_liquidacion_bono_supervisor_individualDataTable cln = ((dt_liquidacion_bono_supervisor_individualDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dt_liquidacion_bono_supervisor_individualDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columncodigo_supervisor = base.Columns["codigo_supervisor"];
                this.columncodigo_empresa = base.Columns["codigo_empresa"];
                this.columnapellidos_nombres_supervisor = base.Columns["apellidos_nombres_supervisor"];
                this.columnnombre_empresa = base.Columns["nombre_empresa"];
                this.columnnombre_grupo = base.Columns["nombre_grupo"];
                this.columnmonto_bruto_empresa_supervisor = base.Columns["monto_bruto_empresa_supervisor"];
                this.columnmonto_igv_empresa_supervisor = base.Columns["monto_igv_empresa_supervisor"];
                this.columnmonto_neto_empresa_supervisor = base.Columns["monto_neto_empresa_supervisor"];
                this.columnmonto_detraccion_empresa_supervisor = base.Columns["monto_detraccion_empresa_supervisor"];
                this.columnnro_documento = base.Columns["nro_documento"];
                this.columnnombre_tipo_documento = base.Columns["nombre_tipo_documento"];
                this.columnruc = base.Columns["ruc"];
                this.columnnombre_empresa_largo = base.Columns["nombre_empresa_largo"];
                this.columndireccion_fiscal = base.Columns["direccion_fiscal"];
                this.columnconcepto = base.Columns["concepto"];
                this.columnporcentaje_detraccion = base.Columns["porcentaje_detraccion"];
                this.columnfecha_inicio = base.Columns["fecha_inicio"];
                this.columnfecha_fin = base.Columns["fecha_fin"];
                this.columncodigo_estado_planilla = base.Columns["codigo_estado_planilla"];
                this.columnmonto_neto_pagar_empresa_supervisor = base.Columns["monto_neto_pagar_empresa_supervisor"];
                this.columnneto_pagar_empresa_supervisor_letra = base.Columns["neto_pagar_empresa_supervisor_letra"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columncodigo_supervisor = new global::System.Data.DataColumn("codigo_supervisor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_supervisor);
                this.columncodigo_empresa = new global::System.Data.DataColumn("codigo_empresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_empresa);
                this.columnapellidos_nombres_supervisor = new global::System.Data.DataColumn("apellidos_nombres_supervisor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnapellidos_nombres_supervisor);
                this.columnnombre_empresa = new global::System.Data.DataColumn("nombre_empresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_empresa);
                this.columnnombre_grupo = new global::System.Data.DataColumn("nombre_grupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_grupo);
                this.columnmonto_bruto_empresa_supervisor = new global::System.Data.DataColumn("monto_bruto_empresa_supervisor", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_bruto_empresa_supervisor);
                this.columnmonto_igv_empresa_supervisor = new global::System.Data.DataColumn("monto_igv_empresa_supervisor", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_igv_empresa_supervisor);
                this.columnmonto_neto_empresa_supervisor = new global::System.Data.DataColumn("monto_neto_empresa_supervisor", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_neto_empresa_supervisor);
                this.columnmonto_detraccion_empresa_supervisor = new global::System.Data.DataColumn("monto_detraccion_empresa_supervisor", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_detraccion_empresa_supervisor);
                this.columnnro_documento = new global::System.Data.DataColumn("nro_documento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnro_documento);
                this.columnnombre_tipo_documento = new global::System.Data.DataColumn("nombre_tipo_documento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_tipo_documento);
                this.columnruc = new global::System.Data.DataColumn("ruc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnruc);
                this.columnnombre_empresa_largo = new global::System.Data.DataColumn("nombre_empresa_largo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_empresa_largo);
                this.columndireccion_fiscal = new global::System.Data.DataColumn("direccion_fiscal", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndireccion_fiscal);
                this.columnconcepto = new global::System.Data.DataColumn("concepto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnconcepto);
                this.columnporcentaje_detraccion = new global::System.Data.DataColumn("porcentaje_detraccion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnporcentaje_detraccion);
                this.columnfecha_inicio = new global::System.Data.DataColumn("fecha_inicio", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfecha_inicio);
                this.columnfecha_fin = new global::System.Data.DataColumn("fecha_fin", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfecha_fin);
                this.columncodigo_estado_planilla = new global::System.Data.DataColumn("codigo_estado_planilla", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_estado_planilla);
                this.columnmonto_neto_pagar_empresa_supervisor = new global::System.Data.DataColumn("monto_neto_pagar_empresa_supervisor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_neto_pagar_empresa_supervisor);
                this.columnneto_pagar_empresa_supervisor_letra = new global::System.Data.DataColumn("neto_pagar_empresa_supervisor_letra", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnneto_pagar_empresa_supervisor_letra);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_liquidacion_bono_supervisor_individualRow Newdt_liquidacion_bono_supervisor_individualRow() {
                return ((dt_liquidacion_bono_supervisor_individualRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dt_liquidacion_bono_supervisor_individualRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dt_liquidacion_bono_supervisor_individualRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dt_liquidacion_bono_supervisor_individualRowChanged != null)) {
                    this.dt_liquidacion_bono_supervisor_individualRowChanged(this, new dt_liquidacion_bono_supervisor_individualRowChangeEvent(((dt_liquidacion_bono_supervisor_individualRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dt_liquidacion_bono_supervisor_individualRowChanging != null)) {
                    this.dt_liquidacion_bono_supervisor_individualRowChanging(this, new dt_liquidacion_bono_supervisor_individualRowChangeEvent(((dt_liquidacion_bono_supervisor_individualRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dt_liquidacion_bono_supervisor_individualRowDeleted != null)) {
                    this.dt_liquidacion_bono_supervisor_individualRowDeleted(this, new dt_liquidacion_bono_supervisor_individualRowChangeEvent(((dt_liquidacion_bono_supervisor_individualRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dt_liquidacion_bono_supervisor_individualRowDeleting != null)) {
                    this.dt_liquidacion_bono_supervisor_individualRowDeleting(this, new dt_liquidacion_bono_supervisor_individualRowChangeEvent(((dt_liquidacion_bono_supervisor_individualRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Removedt_liquidacion_bono_supervisor_individualRow(dt_liquidacion_bono_supervisor_individualRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsLiquidacionBonoSupervisorIndividual ds = new dsLiquidacionBonoSupervisorIndividual();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dt_liquidacion_bono_supervisor_individualDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dt_liquidacion_bono_supervisor_individualRow : global::System.Data.DataRow {
            
            private dt_liquidacion_bono_supervisor_individualDataTable tabledt_liquidacion_bono_supervisor_individual;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dt_liquidacion_bono_supervisor_individualRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledt_liquidacion_bono_supervisor_individual = ((dt_liquidacion_bono_supervisor_individualDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string codigo_supervisor {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_supervisor\' in table \'dt_liquidacion_bono_supervisor" +
                                "_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string codigo_empresa {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_empresa\' in table \'dt_liquidacion_bono_supervisor_in" +
                                "dividual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string apellidos_nombres_supervisor {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.apellidos_nombres_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'apellidos_nombres_supervisor\' in table \'dt_liquidacion_bono" +
                                "_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.apellidos_nombres_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_empresa {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_empresa\' in table \'dt_liquidacion_bono_supervisor_in" +
                                "dividual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_grupo {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_grupo\' in table \'dt_liquidacion_bono_supervisor_indi" +
                                "vidual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_bruto_empresa_supervisor {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_liquidacion_bono_supervisor_individual.monto_bruto_empresa_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_bruto_empresa_supervisor\' in table \'dt_liquidacion_bo" +
                                "no_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.monto_bruto_empresa_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_igv_empresa_supervisor {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_liquidacion_bono_supervisor_individual.monto_igv_empresa_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_igv_empresa_supervisor\' in table \'dt_liquidacion_bono" +
                                "_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.monto_igv_empresa_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_neto_empresa_supervisor {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_empresa_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_neto_empresa_supervisor\' in table \'dt_liquidacion_bon" +
                                "o_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_empresa_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_detraccion_empresa_supervisor {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_liquidacion_bono_supervisor_individual.monto_detraccion_empresa_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_detraccion_empresa_supervisor\' in table \'dt_liquidaci" +
                                "on_bono_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.monto_detraccion_empresa_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nro_documento {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.nro_documentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nro_documento\' in table \'dt_liquidacion_bono_supervisor_ind" +
                                "ividual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.nro_documentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_tipo_documento {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_tipo_documentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_tipo_documento\' in table \'dt_liquidacion_bono_superv" +
                                "isor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_tipo_documentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ruc {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.rucColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ruc\' in table \'dt_liquidacion_bono_supervisor_individual\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.rucColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_empresa_largo {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresa_largoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_empresa_largo\' in table \'dt_liquidacion_bono_supervi" +
                                "sor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresa_largoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string direccion_fiscal {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.direccion_fiscalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'direccion_fiscal\' in table \'dt_liquidacion_bono_supervisor_" +
                                "individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.direccion_fiscalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string concepto {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.conceptoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'concepto\' in table \'dt_liquidacion_bono_supervisor_individu" +
                                "al\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.conceptoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string porcentaje_detraccion {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.porcentaje_detraccionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'porcentaje_detraccion\' in table \'dt_liquidacion_bono_superv" +
                                "isor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.porcentaje_detraccionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fecha_inicio {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.fecha_inicioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fecha_inicio\' in table \'dt_liquidacion_bono_supervisor_indi" +
                                "vidual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.fecha_inicioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fecha_fin {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.fecha_finColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fecha_fin\' in table \'dt_liquidacion_bono_supervisor_individ" +
                                "ual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.fecha_finColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string codigo_estado_planilla {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_estado_planillaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_estado_planilla\' in table \'dt_liquidacion_bono_super" +
                                "visor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_estado_planillaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string monto_neto_pagar_empresa_supervisor {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_pagar_empresa_supervisorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_neto_pagar_empresa_supervisor\' in table \'dt_liquidaci" +
                                "on_bono_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_pagar_empresa_supervisorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string neto_pagar_empresa_supervisor_letra {
                get {
                    try {
                        return ((string)(this[this.tabledt_liquidacion_bono_supervisor_individual.neto_pagar_empresa_supervisor_letraColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'neto_pagar_empresa_supervisor_letra\' in table \'dt_liquidaci" +
                                "on_bono_supervisor_individual\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_liquidacion_bono_supervisor_individual.neto_pagar_empresa_supervisor_letraColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.codigo_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_empresaNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.codigo_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_empresaNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isapellidos_nombres_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.apellidos_nombres_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setapellidos_nombres_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.apellidos_nombres_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_empresaNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_empresaNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_grupoNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.nombre_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_grupoNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_bruto_empresa_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.monto_bruto_empresa_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_bruto_empresa_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.monto_bruto_empresa_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_igv_empresa_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.monto_igv_empresa_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_igv_empresa_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.monto_igv_empresa_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_neto_empresa_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_empresa_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_neto_empresa_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_empresa_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_detraccion_empresa_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.monto_detraccion_empresa_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_detraccion_empresa_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.monto_detraccion_empresa_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnro_documentoNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.nro_documentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnro_documentoNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.nro_documentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_tipo_documentoNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.nombre_tipo_documentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_tipo_documentoNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_tipo_documentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsrucNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.rucColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetrucNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.rucColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_empresa_largoNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresa_largoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_empresa_largoNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.nombre_empresa_largoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdireccion_fiscalNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.direccion_fiscalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdireccion_fiscalNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.direccion_fiscalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsconceptoNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.conceptoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetconceptoNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.conceptoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isporcentaje_detraccionNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.porcentaje_detraccionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setporcentaje_detraccionNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.porcentaje_detraccionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfecha_inicioNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.fecha_inicioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfecha_inicioNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.fecha_inicioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfecha_finNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.fecha_finColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfecha_finNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.fecha_finColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_estado_planillaNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.codigo_estado_planillaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_estado_planillaNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.codigo_estado_planillaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_neto_pagar_empresa_supervisorNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_pagar_empresa_supervisorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_neto_pagar_empresa_supervisorNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.monto_neto_pagar_empresa_supervisorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isneto_pagar_empresa_supervisor_letraNull() {
                return this.IsNull(this.tabledt_liquidacion_bono_supervisor_individual.neto_pagar_empresa_supervisor_letraColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setneto_pagar_empresa_supervisor_letraNull() {
                this[this.tabledt_liquidacion_bono_supervisor_individual.neto_pagar_empresa_supervisor_letraColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dt_liquidacion_bono_supervisor_individualRowChangeEvent : global::System.EventArgs {
            
            private dt_liquidacion_bono_supervisor_individualRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_liquidacion_bono_supervisor_individualRowChangeEvent(dt_liquidacion_bono_supervisor_individualRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_liquidacion_bono_supervisor_individualRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591