//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SIGEES.Web.Areas.Comision.Reporte.PlanillaBono.ds {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsPlanillaBonoPersonal")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsPlanillaBonoPersonal : global::System.Data.DataSet {
        
        private dt_planilla_bono_personalDataTable tabledt_planilla_bono_personal;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsPlanillaBonoPersonal() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsPlanillaBonoPersonal(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dt_planilla_bono_personal"] != null)) {
                    base.Tables.Add(new dt_planilla_bono_personalDataTable(ds.Tables["dt_planilla_bono_personal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dt_planilla_bono_personalDataTable dt_planilla_bono_personal {
            get {
                return this.tabledt_planilla_bono_personal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsPlanillaBonoPersonal cln = ((dsPlanillaBonoPersonal)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dt_planilla_bono_personal"] != null)) {
                    base.Tables.Add(new dt_planilla_bono_personalDataTable(ds.Tables["dt_planilla_bono_personal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledt_planilla_bono_personal = ((dt_planilla_bono_personalDataTable)(base.Tables["dt_planilla_bono_personal"]));
            if ((initTable == true)) {
                if ((this.tabledt_planilla_bono_personal != null)) {
                    this.tabledt_planilla_bono_personal.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsPlanillaBonoPersonal";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsPlanillaBonoPersonal.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledt_planilla_bono_personal = new dt_planilla_bono_personalDataTable();
            base.Tables.Add(this.tabledt_planilla_bono_personal);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializedt_planilla_bono_personal() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsPlanillaBonoPersonal ds = new dsPlanillaBonoPersonal();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dt_planilla_bono_personalRowChangeEventHandler(object sender, dt_planilla_bono_personalRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dt_planilla_bono_personalDataTable : global::System.Data.TypedTableBase<dt_planilla_bono_personalRow> {
            
            private global::System.Data.DataColumn columnfecha_inicio;
            
            private global::System.Data.DataColumn columnfecha_fin;
            
            private global::System.Data.DataColumn columncodigo_personal;
            
            private global::System.Data.DataColumn columnnombres_apellidos;
            
            private global::System.Data.DataColumn columncodigo_empresa;
            
            private global::System.Data.DataColumn columnnombre_empresa;
            
            private global::System.Data.DataColumn columnmonto_contratado_empresa;
            
            private global::System.Data.DataColumn columnmonto_ingresado_empresa;
            
            private global::System.Data.DataColumn columnmonto_bruto_empresa;
            
            private global::System.Data.DataColumn columnmonto_igv_empresa;
            
            private global::System.Data.DataColumn columndetraccion_empresa;
            
            private global::System.Data.DataColumn columnmonto_neto_empresa;
            
            private global::System.Data.DataColumn columncodigo_grupo;
            
            private global::System.Data.DataColumn columnnombre_grupo;
            
            private global::System.Data.DataColumn columnmonto_contrato_grupo;
            
            private global::System.Data.DataColumn columnmonto_ingresado_grupo;
            
            private global::System.Data.DataColumn columnporcentaje_pago;
            
            private global::System.Data.DataColumn columnmeta_logrado;
            
            private global::System.Data.DataColumn columnmonto_neto_grupo;
            
            private global::System.Data.DataColumn columnmonto_igv_grupo;
            
            private global::System.Data.DataColumn columnmonto_bruto_grupo;
            
            private global::System.Data.DataColumn columnnombre_canal;
            
            private global::System.Data.DataColumn columncodigo_estado_planilla;
            
            private global::System.Data.DataColumn columnmonto_neto_bono_empresa;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_planilla_bono_personalDataTable() {
                this.TableName = "dt_planilla_bono_personal";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dt_planilla_bono_personalDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dt_planilla_bono_personalDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fecha_inicioColumn {
                get {
                    return this.columnfecha_inicio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fecha_finColumn {
                get {
                    return this.columnfecha_fin;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_personalColumn {
                get {
                    return this.columncodigo_personal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombres_apellidosColumn {
                get {
                    return this.columnnombres_apellidos;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_empresaColumn {
                get {
                    return this.columncodigo_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_empresaColumn {
                get {
                    return this.columnnombre_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_contratado_empresaColumn {
                get {
                    return this.columnmonto_contratado_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_ingresado_empresaColumn {
                get {
                    return this.columnmonto_ingresado_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_bruto_empresaColumn {
                get {
                    return this.columnmonto_bruto_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_igv_empresaColumn {
                get {
                    return this.columnmonto_igv_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn detraccion_empresaColumn {
                get {
                    return this.columndetraccion_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_neto_empresaColumn {
                get {
                    return this.columnmonto_neto_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_grupoColumn {
                get {
                    return this.columncodigo_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_grupoColumn {
                get {
                    return this.columnnombre_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_contrato_grupoColumn {
                get {
                    return this.columnmonto_contrato_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_ingresado_grupoColumn {
                get {
                    return this.columnmonto_ingresado_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn porcentaje_pagoColumn {
                get {
                    return this.columnporcentaje_pago;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn meta_logradoColumn {
                get {
                    return this.columnmeta_logrado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_neto_grupoColumn {
                get {
                    return this.columnmonto_neto_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_igv_grupoColumn {
                get {
                    return this.columnmonto_igv_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_bruto_grupoColumn {
                get {
                    return this.columnmonto_bruto_grupo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nombre_canalColumn {
                get {
                    return this.columnnombre_canal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn codigo_estado_planillaColumn {
                get {
                    return this.columncodigo_estado_planilla;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn monto_neto_bono_empresaColumn {
                get {
                    return this.columnmonto_neto_bono_empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_planilla_bono_personalRow this[int index] {
                get {
                    return ((dt_planilla_bono_personalRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_planilla_bono_personalRowChangeEventHandler dt_planilla_bono_personalRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_planilla_bono_personalRowChangeEventHandler dt_planilla_bono_personalRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_planilla_bono_personalRowChangeEventHandler dt_planilla_bono_personalRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dt_planilla_bono_personalRowChangeEventHandler dt_planilla_bono_personalRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Adddt_planilla_bono_personalRow(dt_planilla_bono_personalRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_planilla_bono_personalRow Adddt_planilla_bono_personalRow(
                        string fecha_inicio, 
                        string fecha_fin, 
                        int codigo_personal, 
                        string nombres_apellidos, 
                        int codigo_empresa, 
                        string nombre_empresa, 
                        decimal monto_contratado_empresa, 
                        decimal monto_ingresado_empresa, 
                        decimal monto_bruto_empresa, 
                        decimal monto_igv_empresa, 
                        decimal detraccion_empresa, 
                        decimal monto_neto_empresa, 
                        int codigo_grupo, 
                        string nombre_grupo, 
                        decimal monto_contrato_grupo, 
                        decimal monto_ingresado_grupo, 
                        decimal porcentaje_pago, 
                        decimal meta_logrado, 
                        decimal monto_neto_grupo, 
                        decimal monto_igv_grupo, 
                        decimal monto_bruto_grupo, 
                        string nombre_canal, 
                        int codigo_estado_planilla, 
                        decimal monto_neto_bono_empresa) {
                dt_planilla_bono_personalRow rowdt_planilla_bono_personalRow = ((dt_planilla_bono_personalRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        fecha_inicio,
                        fecha_fin,
                        codigo_personal,
                        nombres_apellidos,
                        codigo_empresa,
                        nombre_empresa,
                        monto_contratado_empresa,
                        monto_ingresado_empresa,
                        monto_bruto_empresa,
                        monto_igv_empresa,
                        detraccion_empresa,
                        monto_neto_empresa,
                        codigo_grupo,
                        nombre_grupo,
                        monto_contrato_grupo,
                        monto_ingresado_grupo,
                        porcentaje_pago,
                        meta_logrado,
                        monto_neto_grupo,
                        monto_igv_grupo,
                        monto_bruto_grupo,
                        nombre_canal,
                        codigo_estado_planilla,
                        monto_neto_bono_empresa};
                rowdt_planilla_bono_personalRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdt_planilla_bono_personalRow);
                return rowdt_planilla_bono_personalRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dt_planilla_bono_personalDataTable cln = ((dt_planilla_bono_personalDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dt_planilla_bono_personalDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnfecha_inicio = base.Columns["fecha_inicio"];
                this.columnfecha_fin = base.Columns["fecha_fin"];
                this.columncodigo_personal = base.Columns["codigo_personal"];
                this.columnnombres_apellidos = base.Columns["nombres_apellidos"];
                this.columncodigo_empresa = base.Columns["codigo_empresa"];
                this.columnnombre_empresa = base.Columns["nombre_empresa"];
                this.columnmonto_contratado_empresa = base.Columns["monto_contratado_empresa"];
                this.columnmonto_ingresado_empresa = base.Columns["monto_ingresado_empresa"];
                this.columnmonto_bruto_empresa = base.Columns["monto_bruto_empresa"];
                this.columnmonto_igv_empresa = base.Columns["monto_igv_empresa"];
                this.columndetraccion_empresa = base.Columns["detraccion_empresa"];
                this.columnmonto_neto_empresa = base.Columns["monto_neto_empresa"];
                this.columncodigo_grupo = base.Columns["codigo_grupo"];
                this.columnnombre_grupo = base.Columns["nombre_grupo"];
                this.columnmonto_contrato_grupo = base.Columns["monto_contrato_grupo"];
                this.columnmonto_ingresado_grupo = base.Columns["monto_ingresado_grupo"];
                this.columnporcentaje_pago = base.Columns["porcentaje_pago"];
                this.columnmeta_logrado = base.Columns["meta_logrado"];
                this.columnmonto_neto_grupo = base.Columns["monto_neto_grupo"];
                this.columnmonto_igv_grupo = base.Columns["monto_igv_grupo"];
                this.columnmonto_bruto_grupo = base.Columns["monto_bruto_grupo"];
                this.columnnombre_canal = base.Columns["nombre_canal"];
                this.columncodigo_estado_planilla = base.Columns["codigo_estado_planilla"];
                this.columnmonto_neto_bono_empresa = base.Columns["monto_neto_bono_empresa"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnfecha_inicio = new global::System.Data.DataColumn("fecha_inicio", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfecha_inicio);
                this.columnfecha_fin = new global::System.Data.DataColumn("fecha_fin", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfecha_fin);
                this.columncodigo_personal = new global::System.Data.DataColumn("codigo_personal", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_personal);
                this.columnnombres_apellidos = new global::System.Data.DataColumn("nombres_apellidos", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombres_apellidos);
                this.columncodigo_empresa = new global::System.Data.DataColumn("codigo_empresa", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_empresa);
                this.columnnombre_empresa = new global::System.Data.DataColumn("nombre_empresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_empresa);
                this.columnmonto_contratado_empresa = new global::System.Data.DataColumn("monto_contratado_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_contratado_empresa);
                this.columnmonto_ingresado_empresa = new global::System.Data.DataColumn("monto_ingresado_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_ingresado_empresa);
                this.columnmonto_bruto_empresa = new global::System.Data.DataColumn("monto_bruto_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_bruto_empresa);
                this.columnmonto_igv_empresa = new global::System.Data.DataColumn("monto_igv_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_igv_empresa);
                this.columndetraccion_empresa = new global::System.Data.DataColumn("detraccion_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndetraccion_empresa);
                this.columnmonto_neto_empresa = new global::System.Data.DataColumn("monto_neto_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_neto_empresa);
                this.columncodigo_grupo = new global::System.Data.DataColumn("codigo_grupo", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_grupo);
                this.columnnombre_grupo = new global::System.Data.DataColumn("nombre_grupo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_grupo);
                this.columnmonto_contrato_grupo = new global::System.Data.DataColumn("monto_contrato_grupo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_contrato_grupo);
                this.columnmonto_ingresado_grupo = new global::System.Data.DataColumn("monto_ingresado_grupo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_ingresado_grupo);
                this.columnporcentaje_pago = new global::System.Data.DataColumn("porcentaje_pago", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnporcentaje_pago);
                this.columnmeta_logrado = new global::System.Data.DataColumn("meta_logrado", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmeta_logrado);
                this.columnmonto_neto_grupo = new global::System.Data.DataColumn("monto_neto_grupo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_neto_grupo);
                this.columnmonto_igv_grupo = new global::System.Data.DataColumn("monto_igv_grupo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_igv_grupo);
                this.columnmonto_bruto_grupo = new global::System.Data.DataColumn("monto_bruto_grupo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_bruto_grupo);
                this.columnnombre_canal = new global::System.Data.DataColumn("nombre_canal", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombre_canal);
                this.columncodigo_estado_planilla = new global::System.Data.DataColumn("codigo_estado_planilla", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo_estado_planilla);
                this.columnmonto_neto_bono_empresa = new global::System.Data.DataColumn("monto_neto_bono_empresa", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmonto_neto_bono_empresa);
                this.columnmonto_contrato_grupo.DefaultValue = ((decimal)(0.00m));
                this.columnmonto_ingresado_grupo.DefaultValue = ((decimal)(0.00m));
                this.columnmeta_logrado.DefaultValue = ((decimal)(0.00m));
                this.columnmonto_neto_grupo.DefaultValue = ((decimal)(0.00m));
                this.columnmonto_igv_grupo.DefaultValue = ((decimal)(0.00m));
                this.columnmonto_bruto_grupo.DefaultValue = ((decimal)(0.00m));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_planilla_bono_personalRow Newdt_planilla_bono_personalRow() {
                return ((dt_planilla_bono_personalRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dt_planilla_bono_personalRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dt_planilla_bono_personalRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dt_planilla_bono_personalRowChanged != null)) {
                    this.dt_planilla_bono_personalRowChanged(this, new dt_planilla_bono_personalRowChangeEvent(((dt_planilla_bono_personalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dt_planilla_bono_personalRowChanging != null)) {
                    this.dt_planilla_bono_personalRowChanging(this, new dt_planilla_bono_personalRowChangeEvent(((dt_planilla_bono_personalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dt_planilla_bono_personalRowDeleted != null)) {
                    this.dt_planilla_bono_personalRowDeleted(this, new dt_planilla_bono_personalRowChangeEvent(((dt_planilla_bono_personalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dt_planilla_bono_personalRowDeleting != null)) {
                    this.dt_planilla_bono_personalRowDeleting(this, new dt_planilla_bono_personalRowChangeEvent(((dt_planilla_bono_personalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Removedt_planilla_bono_personalRow(dt_planilla_bono_personalRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsPlanillaBonoPersonal ds = new dsPlanillaBonoPersonal();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dt_planilla_bono_personalDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dt_planilla_bono_personalRow : global::System.Data.DataRow {
            
            private dt_planilla_bono_personalDataTable tabledt_planilla_bono_personal;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dt_planilla_bono_personalRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledt_planilla_bono_personal = ((dt_planilla_bono_personalDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fecha_inicio {
                get {
                    try {
                        return ((string)(this[this.tabledt_planilla_bono_personal.fecha_inicioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fecha_inicio\' in table \'dt_planilla_bono_personal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.fecha_inicioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fecha_fin {
                get {
                    try {
                        return ((string)(this[this.tabledt_planilla_bono_personal.fecha_finColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fecha_fin\' in table \'dt_planilla_bono_personal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.fecha_finColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_personal {
                get {
                    try {
                        return ((int)(this[this.tabledt_planilla_bono_personal.codigo_personalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_personal\' in table \'dt_planilla_bono_personal\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.codigo_personalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombres_apellidos {
                get {
                    try {
                        return ((string)(this[this.tabledt_planilla_bono_personal.nombres_apellidosColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombres_apellidos\' in table \'dt_planilla_bono_personal\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.nombres_apellidosColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_empresa {
                get {
                    try {
                        return ((int)(this[this.tabledt_planilla_bono_personal.codigo_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_empresa\' in table \'dt_planilla_bono_personal\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.codigo_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_empresa {
                get {
                    try {
                        return ((string)(this[this.tabledt_planilla_bono_personal.nombre_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_empresa\' in table \'dt_planilla_bono_personal\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.nombre_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_contratado_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_contratado_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_contratado_empresa\' in table \'dt_planilla_bono_person" +
                                "al\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_contratado_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_ingresado_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_ingresado_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_ingresado_empresa\' in table \'dt_planilla_bono_persona" +
                                "l\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_ingresado_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_bruto_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_bruto_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_bruto_empresa\' in table \'dt_planilla_bono_personal\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_bruto_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_igv_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_igv_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_igv_empresa\' in table \'dt_planilla_bono_personal\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_igv_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal detraccion_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.detraccion_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'detraccion_empresa\' in table \'dt_planilla_bono_personal\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.detraccion_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_neto_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_neto_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_neto_empresa\' in table \'dt_planilla_bono_personal\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_neto_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_grupo {
                get {
                    try {
                        return ((int)(this[this.tabledt_planilla_bono_personal.codigo_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_grupo\' in table \'dt_planilla_bono_personal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.codigo_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_grupo {
                get {
                    try {
                        return ((string)(this[this.tabledt_planilla_bono_personal.nombre_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_grupo\' in table \'dt_planilla_bono_personal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.nombre_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_contrato_grupo {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_contrato_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_contrato_grupo\' in table \'dt_planilla_bono_personal\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_contrato_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_ingresado_grupo {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_ingresado_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_ingresado_grupo\' in table \'dt_planilla_bono_personal\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_ingresado_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal porcentaje_pago {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.porcentaje_pagoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'porcentaje_pago\' in table \'dt_planilla_bono_personal\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.porcentaje_pagoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal meta_logrado {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.meta_logradoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'meta_logrado\' in table \'dt_planilla_bono_personal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.meta_logradoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_neto_grupo {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_neto_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_neto_grupo\' in table \'dt_planilla_bono_personal\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_neto_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_igv_grupo {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_igv_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_igv_grupo\' in table \'dt_planilla_bono_personal\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_igv_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_bruto_grupo {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_bruto_grupoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_bruto_grupo\' in table \'dt_planilla_bono_personal\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_bruto_grupoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nombre_canal {
                get {
                    try {
                        return ((string)(this[this.tabledt_planilla_bono_personal.nombre_canalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nombre_canal\' in table \'dt_planilla_bono_personal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.nombre_canalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int codigo_estado_planilla {
                get {
                    try {
                        return ((int)(this[this.tabledt_planilla_bono_personal.codigo_estado_planillaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'codigo_estado_planilla\' in table \'dt_planilla_bono_personal" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.codigo_estado_planillaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal monto_neto_bono_empresa {
                get {
                    try {
                        return ((decimal)(this[this.tabledt_planilla_bono_personal.monto_neto_bono_empresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'monto_neto_bono_empresa\' in table \'dt_planilla_bono_persona" +
                                "l\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledt_planilla_bono_personal.monto_neto_bono_empresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfecha_inicioNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.fecha_inicioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfecha_inicioNull() {
                this[this.tabledt_planilla_bono_personal.fecha_inicioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfecha_finNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.fecha_finColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfecha_finNull() {
                this[this.tabledt_planilla_bono_personal.fecha_finColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_personalNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.codigo_personalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_personalNull() {
                this[this.tabledt_planilla_bono_personal.codigo_personalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombres_apellidosNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.nombres_apellidosColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombres_apellidosNull() {
                this[this.tabledt_planilla_bono_personal.nombres_apellidosColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.codigo_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_empresaNull() {
                this[this.tabledt_planilla_bono_personal.codigo_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.nombre_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_empresaNull() {
                this[this.tabledt_planilla_bono_personal.nombre_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_contratado_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_contratado_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_contratado_empresaNull() {
                this[this.tabledt_planilla_bono_personal.monto_contratado_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_ingresado_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_ingresado_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_ingresado_empresaNull() {
                this[this.tabledt_planilla_bono_personal.monto_ingresado_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_bruto_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_bruto_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_bruto_empresaNull() {
                this[this.tabledt_planilla_bono_personal.monto_bruto_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_igv_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_igv_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_igv_empresaNull() {
                this[this.tabledt_planilla_bono_personal.monto_igv_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdetraccion_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.detraccion_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdetraccion_empresaNull() {
                this[this.tabledt_planilla_bono_personal.detraccion_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_neto_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_neto_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_neto_empresaNull() {
                this[this.tabledt_planilla_bono_personal.monto_neto_empresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.codigo_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_grupoNull() {
                this[this.tabledt_planilla_bono_personal.codigo_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.nombre_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_grupoNull() {
                this[this.tabledt_planilla_bono_personal.nombre_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_contrato_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_contrato_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_contrato_grupoNull() {
                this[this.tabledt_planilla_bono_personal.monto_contrato_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_ingresado_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_ingresado_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_ingresado_grupoNull() {
                this[this.tabledt_planilla_bono_personal.monto_ingresado_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isporcentaje_pagoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.porcentaje_pagoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setporcentaje_pagoNull() {
                this[this.tabledt_planilla_bono_personal.porcentaje_pagoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismeta_logradoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.meta_logradoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmeta_logradoNull() {
                this[this.tabledt_planilla_bono_personal.meta_logradoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_neto_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_neto_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_neto_grupoNull() {
                this[this.tabledt_planilla_bono_personal.monto_neto_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_igv_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_igv_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_igv_grupoNull() {
                this[this.tabledt_planilla_bono_personal.monto_igv_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_bruto_grupoNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_bruto_grupoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_bruto_grupoNull() {
                this[this.tabledt_planilla_bono_personal.monto_bruto_grupoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isnombre_canalNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.nombre_canalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setnombre_canalNull() {
                this[this.tabledt_planilla_bono_personal.nombre_canalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iscodigo_estado_planillaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.codigo_estado_planillaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcodigo_estado_planillaNull() {
                this[this.tabledt_planilla_bono_personal.codigo_estado_planillaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismonto_neto_bono_empresaNull() {
                return this.IsNull(this.tabledt_planilla_bono_personal.monto_neto_bono_empresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmonto_neto_bono_empresaNull() {
                this[this.tabledt_planilla_bono_personal.monto_neto_bono_empresaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dt_planilla_bono_personalRowChangeEvent : global::System.EventArgs {
            
            private dt_planilla_bono_personalRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_planilla_bono_personalRowChangeEvent(dt_planilla_bono_personalRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dt_planilla_bono_personalRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591