//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabecera_lapida
    {
        public cabecera_lapida()
        {
            this.detalle_grupo_lapida = new HashSet<detalle_grupo_lapida>();
            this.lapida = new HashSet<lapida>();
        }
    
        public int codigo_cabecera_lapida { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
        public int codigo_estado_lapida { get; set; }
        public string codigo_espacio { get; set; }
        public Nullable<System.DateTime> fecha_inicio_confeccion { get; set; }
        public Nullable<System.DateTime> fecha_fin_confeccion { get; set; }
        public Nullable<System.DateTime> fecha_colocacion { get; set; }
    
        public virtual espacio espacio { get; set; }
        public virtual estado_lapida estado_lapida { get; set; }
        public virtual ICollection<detalle_grupo_lapida> detalle_grupo_lapida { get; set; }
        public virtual ICollection<lapida> lapida { get; set; }
    }
}
