//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_grupo_lapida
    {
        public int codigo_detalle { get; set; }
        public int codigo_grupo_lapida { get; set; }
        public int codigo_cabecera_lapida { get; set; }
        public bool estado_registro { get; set; }
    
        public virtual cabecera_lapida cabecera_lapida { get; set; }
        public virtual grupo_lapida grupo_lapida { get; set; }
    }
}
