//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_estado_espacio
    {
        public int codigo_det_estado_espcio { get; set; }
        public string codigo_espacio { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public int codigo_estado_espacio { get; set; }
    
        public virtual espacio espacio { get; set; }
        public virtual estado_espacio estado_espacio { get; set; }
    }
}
