//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_movimiento_tabla
    {
        public estado_movimiento_tabla()
        {
            this.reserva = new HashSet<reserva>();
            this.venta = new HashSet<venta>();
        }
    
        public int codigo_estado_movimiento_tabla { get; set; }
        public string nombre_estado_movimiento_tabla { get; set; }
        public bool estado_registro { get; set; }
        public string descripcion { get; set; }
        public int tabla { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_registro { get; set; }
    
        public virtual ICollection<reserva> reserva { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
