//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exhumacion_fallecido
    {
        public exhumacion_fallecido()
        {
            this.detalle_exhumacion = new HashSet<detalle_exhumacion>();
        }
    
        public int codigo_exhumacion { get; set; }
        public Nullable<System.DateTime> exhumacion_fecha_inicio { get; set; }
        public string exhumacion_informe_inicio { get; set; }
        public string exhumacion_observacion_inicio { get; set; }
        public Nullable<System.DateTime> exhumacion_fecha_final { get; set; }
        public string exhumacion_informe_final { get; set; }
        public string exhumacion_observacion_final { get; set; }
        public int codigo_fallecido { get; set; }
        public string codigo_espacio { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public string usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_modifica { get; set; }
        public int codigo_estado_exhumacion { get; set; }
    
        public virtual ICollection<detalle_exhumacion> detalle_exhumacion { get; set; }
        public virtual espacio espacio { get; set; }
        public virtual fallecido fallecido { get; set; }
    }
}
