//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fallecido
    {
        public fallecido()
        {
            this.exhumacion_fallecido = new HashSet<exhumacion_fallecido>();
            this.registro_fallecido = new HashSet<registro_fallecido>();
            this.registro_incinerado = new HashSet<registro_incinerado>();
            this.lapida = new HashSet<lapida>();
        }
    
        public int codigo_fallecido { get; set; }
        public Nullable<int> codigo_campo_santo { get; set; }
        public Nullable<int> codigo_persona { get; set; }
        public string numero_contrato { get; set; }
        public int codigo_tipo_fallecido { get; set; }
        public string numero_documento { get; set; }
        public int codigo_tipo_documento { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string nombres { get; set; }
        public int edad { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public System.DateTime fecha_defuncion { get; set; }
        public Nullable<System.DateTime> fecha_traslado_plaza { get; set; }
        public Nullable<int> codigo_motivo_traslado { get; set; }
        public string observacion_traslado { get; set; }
        public string codigo_sexo { get; set; }
        public Nullable<int> codigo_agencia { get; set; }
        public Nullable<int> codigo_nivel_servicio { get; set; }
        public Nullable<int> codigo_caracteristica_lote { get; set; }
        public Nullable<int> codigo_tipo_bien_servicio { get; set; }
        public Nullable<int> codigo_tipo_bien { get; set; }
        public Nullable<int> codigo_tipo_traslado { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual agencia agencia { get; set; }
        public virtual campo_santo campo_santo { get; set; }
        public virtual ICollection<exhumacion_fallecido> exhumacion_fallecido { get; set; }
        public virtual ICollection<registro_fallecido> registro_fallecido { get; set; }
        public virtual ICollection<registro_incinerado> registro_incinerado { get; set; }
        public virtual ICollection<lapida> lapida { get; set; }
        public virtual persona persona { get; set; }
        public virtual tipo_fallecido tipo_fallecido { get; set; }
        public virtual tipo_traslado tipo_traslado { get; set; }
    }
}
