//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_tipo_acceso
    {
        public int codigo_item_tipo_acceso { get; set; }
        public int codigo_tipo_acceso_item { get; set; }
        public int codigo_perfil_usuario { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public string usuario_registra { get; set; }
    
        public virtual perfil_usuario perfil_usuario { get; set; }
        public virtual tipo_acceso_item tipo_acceso_item { get; set; }
    }
}
