//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_usuario
    {
        public perfil_usuario()
        {
            this.item_tipo_acceso = new HashSet<item_tipo_acceso>();
            this.usuario = new HashSet<usuario>();
            this.permiso_menu = new HashSet<permiso_menu>();
        }
    
        public int codigo_perfil_usuario { get; set; }
        public string nombre_perfil_usuario { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual ICollection<item_tipo_acceso> item_tipo_acceso { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual ICollection<permiso_menu> permiso_menu { get; set; }
    }
}
