//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.cliente = new HashSet<cliente>();
            this.fallecido = new HashSet<fallecido>();
            this.reserva = new HashSet<reserva>();
            this.usuario = new HashSet<usuario>();
            this.venta = new HashSet<venta>();
        }
    
        public int codigo_persona { get; set; }
        public int codigo_corporacion { get; set; }
        public int codigo_tipo_documento { get; set; }
        public int codigo_estado_civil { get; set; }
        public string nombre_persona { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string codigo_sexo { get; set; }
        public string numero_documento { get; set; }
        public bool es_vendedor { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual corporacion corporacion { get; set; }
        public virtual estado_civil estado_civil { get; set; }
        public virtual ICollection<fallecido> fallecido { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual ICollection<venta> venta { get; set; }
        public virtual sexo sexo { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
    }
}
