//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sector
    {
        public sector()
        {
            this.edificio = new HashSet<edificio>();
            this.espacio = new HashSet<espacio>();
        }
    
        public int id_sector { get; set; }
        public string codigo_sector { get; set; }
        public int numero_sector { get; set; }
        public int codigo_plataforma { get; set; }
        public Nullable<int> eje_x_numero { get; set; }
        public string eje_x { get; set; }
        public string eje_y { get; set; }
        public string eje_x_superior { get; set; }
        public string eje_y_superior { get; set; }
        public bool es_nuevo { get; set; }
        public int estado { get; set; }
        public string nombre_pabellon { get; set; }
        public string identificador_pabellon { get; set; }
        public Nullable<int> numero_pisos_pabellon { get; set; }
        public Nullable<int> numero_columna_pabellon { get; set; }
        public Nullable<int> codigo_piso_pabellon { get; set; }
        public bool tiene_pabellon { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual ICollection<edificio> edificio { get; set; }
        public virtual ICollection<espacio> espacio { get; set; }
        public virtual plataforma plataforma { get; set; }
    }
}
