//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGEESEntities : DbContext
    {
        public SIGEESEntities()
            : base("name=SIGEESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agencia> agencia { get; set; }
        public virtual DbSet<articulo_cronograma> articulo_cronograma { get; set; }
        public virtual DbSet<cabecera_lapida> cabecera_lapida { get; set; }
        public virtual DbSet<campo_santo> campo_santo { get; set; }
        public virtual DbSet<caracteristica_lote> caracteristica_lote { get; set; }
        public virtual DbSet<clave_usuario> clave_usuario { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<conversion_espacio> conversion_espacio { get; set; }
        public virtual DbSet<corporacion> corporacion { get; set; }
        public virtual DbSet<detalle_atributo> detalle_atributo { get; set; }
        public virtual DbSet<detalle_conversion_espacio> detalle_conversion_espacio { get; set; }
        public virtual DbSet<detalle_entidad> detalle_entidad { get; set; }
        public virtual DbSet<detalle_estado_espacio> detalle_estado_espacio { get; set; }
        public virtual DbSet<detalle_exhumacion> detalle_exhumacion { get; set; }
        public virtual DbSet<detalle_grupo_lapida> detalle_grupo_lapida { get; set; }
        public virtual DbSet<detalle_producto> detalle_producto { get; set; }
        public virtual DbSet<edificio> edificio { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<espacio> espacio { get; set; }
        public virtual DbSet<estado_civil> estado_civil { get; set; }
        public virtual DbSet<estado_conversion> estado_conversion { get; set; }
        public virtual DbSet<estado_espacio> estado_espacio { get; set; }
        public virtual DbSet<estado_exhumacion> estado_exhumacion { get; set; }
        public virtual DbSet<estado_fallecido> estado_fallecido { get; set; }
        public virtual DbSet<estado_lapida> estado_lapida { get; set; }
        public virtual DbSet<estado_movimiento_tabla> estado_movimiento_tabla { get; set; }
        public virtual DbSet<evento_usuario> evento_usuario { get; set; }
        public virtual DbSet<exhumacion_fallecido> exhumacion_fallecido { get; set; }
        public virtual DbSet<fallecido> fallecido { get; set; }
        public virtual DbSet<grupo_lapida> grupo_lapida { get; set; }
        public virtual DbSet<item_tipo_acceso> item_tipo_acceso { get; set; }
        public virtual DbSet<lapida> lapida { get; set; }
        public virtual DbSet<mensaje_sistema> mensaje_sistema { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<motivo_traslado> motivo_traslado { get; set; }
        public virtual DbSet<nivel_servicio> nivel_servicio { get; set; }
        public virtual DbSet<parametro_sistema> parametro_sistema { get; set; }
        public virtual DbSet<perfil_usuario> perfil_usuario { get; set; }
        public virtual DbSet<permiso_empresa> permiso_empresa { get; set; }
        public virtual DbSet<permiso_menu> permiso_menu { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<piso_pabellon> piso_pabellon { get; set; }
        public virtual DbSet<planilla_empresa> planilla_empresa { get; set; }
        public virtual DbSet<plataforma> plataforma { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<registro_fallecido> registro_fallecido { get; set; }
        public virtual DbSet<registro_incinerado> registro_incinerado { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<sector> sector { get; set; }
        public virtual DbSet<sesion_usuario> sesion_usuario { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<tipo_acceso_item> tipo_acceso_item { get; set; }
        public virtual DbSet<tipo_bien> tipo_bien { get; set; }
        public virtual DbSet<tipo_bien_servicio> tipo_bien_servicio { get; set; }
        public virtual DbSet<tipo_conversion_espacio> tipo_conversion_espacio { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tipo_espacio> tipo_espacio { get; set; }
        public virtual DbSet<tipo_evento> tipo_evento { get; set; }
        public virtual DbSet<tipo_fallecido> tipo_fallecido { get; set; }
        public virtual DbSet<tipo_nivel> tipo_nivel { get; set; }
        public virtual DbSet<tipo_piso> tipo_piso { get; set; }
        public virtual DbSet<tipo_plataforma> tipo_plataforma { get; set; }
        public virtual DbSet<tipo_producto> tipo_producto { get; set; }
        public virtual DbSet<tipo_traslado> tipo_traslado { get; set; }        
        public virtual DbSet<TreeNode> TreeNode { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<vista_pabellon> vista_pabellon { get; set; }
        public virtual DbSet<encofrado> encofrado { get; set; }
    }
}
