//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_nivel
    {
        public tipo_nivel()
        {
            this.espacio = new HashSet<espacio>();
            this.lapida = new HashSet<lapida>();
            this.tipo_conversion_espacio = new HashSet<tipo_conversion_espacio>();
        }
    
        public string codigo_tipo_nivel { get; set; }
        public string nombre_tipo_nivel { get; set; }
        public int cantidad { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual ICollection<espacio> espacio { get; set; }
        public virtual ICollection<lapida> lapida { get; set; }
        public virtual ICollection<tipo_conversion_espacio> tipo_conversion_espacio { get; set; }
    }
}
