//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int codigo_venta { get; set; }
        public int codigo_persona { get; set; }
        public Nullable<int> codigo_documento { get; set; }
        public string numero_documento_cliente { get; set; }
        public string ape_paterno_cliente { get; set; }
        public string ape_materno_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> codigo_producto { get; set; }
        public int codigo_reserva { get; set; }
        public bool estado_registro { get; set; }
        public string numero_contrato { get; set; }
        public string codigo_espacio { get; set; }
        public string observacion { get; set; }
        public string observacion_anulacion { get; set; }
        public bool es_venta_manual { get; set; }
        public decimal precio_venta { get; set; }
        public bool indica_pago_espacio { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
        public string motivo_movimiento { get; set; }
        public int codigo_catalogo_bien_contrato { get; set; }
        public int codigo_catalogo_bien_espacio { get; set; }
        public int codigo_caracteristica_lote { get; set; }
        public int codigo_estado_movimiento_tabla { get; set; }
    
        public virtual caracteristica_lote caracteristica_lote { get; set; }
        public virtual estado_movimiento_tabla estado_movimiento_tabla { get; set; }
        public virtual persona persona { get; set; }
        public virtual producto producto { get; set; }
        public virtual tipo_bien tipo_bien { get; set; }
        public virtual tipo_bien tipo_bien1 { get; set; }
    }
}
