CREATE TABLE [dbo].[AGENTE_DB2] (
    [C_AGENTE]          VARCHAR (10)    NOT NULL,
    [COD_EMPRESA_G]     VARCHAR (4)     NOT NULL,
    [COD_GRUPO_VENTA_G] VARCHAR (4)     NULL,
    [TIPO_AGENTE_G]     VARCHAR (4)     NULL,
    [COD_AGENCIA]       VARCHAR (10)    NULL,
    [NOMBRE]            VARCHAR (40)    NULL,
    [APELLIDO_PATERNO]  VARCHAR (25)    NULL,
    [APELLIDO_MATERNO]  VARCHAR (25)    NULL,
    [NOMBRE_CONTAC1]    VARCHAR (40)    NULL,
    [D_AGENTE]          VARCHAR (80)    NULL,
    [C_CARGO_CONTAC1]   CHAR (2)        NULL,
    [TELEF_CONTAC1]     VARCHAR (7)     NULL,
    [CELULAR_CONTAC1]   VARCHAR (7)     NULL,
    [DIREC_CONTAC1]     VARCHAR (40)    NULL,
    [NOMBRE_CONTAC2]    VARCHAR (40)    NULL,
    [C_CARGO_CONTAC2]   VARCHAR (2)     NULL,
    [TELEF_CONTAC2]     VARCHAR (7)     NULL,
    [CELULAR_CONTAC2]   VARCHAR (7)     NULL,
    [DIREC_CONTAC2]     VARCHAR (50)    NULL,
    [COD_DOC]           VARCHAR (4)     NULL,
    [NUM_DOC]           VARCHAR (20)    NULL,
    [RUC]               VARCHAR (15)    NULL,
    [FLAG_RETENSION]    CHAR (1)        NULL,
    [FLAG_RENTA]        VARCHAR (1)     NULL,
    [FLAG_IGV]          VARCHAR (1)     NULL,
    [FLAG_IES]          VARCHAR (1)     NULL,
    [FEC_RENTA]         DATE            NULL,
    [FEC_IGV]           DATE            NULL,
    [FEC_IES]           DATE            NULL,
    [FECHA_INICIO]      DATE            NULL,
    [FECHA_CESE]        DATE            NULL,
    [TELEFONOS]         VARCHAR (30)    NULL,
    [CELULAR]           VARCHAR (30)    NULL,
    [DIRECCION]         VARCHAR (100)   NULL,
    [C_COD_POSTAL]      VARCHAR (5)     NULL,
    [ID_PISO]           VARCHAR (4)     NULL,
    [FLAG_VIGENTE]      VARCHAR (1)     NULL,
    [TIPO_PERSONA]      VARCHAR (4)     NULL,
    [PUEDE_VENDER]      VARCHAR (1)     NULL,
    [FEC_ULT_LIQUI]     DATE            NULL,
    [ULT_NUM_LIQUI]     VARCHAR (10)    NULL,
    [TIPO_TRAB]         VARCHAR (4)     NULL,
    [FEC_MODI]          DATE            NULL,
    [COD_USUARIO]       VARCHAR (10)    NULL,
    [D_AGENTE_T]        VARCHAR (90)    NULL,
    [FLG_LIBRE]         CHAR (1)        NULL,
    [FLAG_PROCESAR]     CHAR (1)        NULL,
    [TIPO_CUENTA]       VARCHAR (4)     NULL,
    [NUMERO_CUENTA]     VARCHAR (20)    NULL,
    [COD_MONEDA]        VARCHAR (4)     NULL,
    [C_PERSONA]         VARCHAR (6)     NULL,
    [TIPO_NOMBRE_OTRO]  CHAR (1)        NULL,
    [AP_PATERNO_OTRO]   VARCHAR (25)    NULL,
    [AP_MATERNO_OTRO]   VARCHAR (25)    NULL,
    [NOMBRE_OTRO]       VARCHAR (40)    NULL,
    [COD_PARENTESCO]    VARCHAR (4)     NULL,
    [COD_DOC2]          VARCHAR (4)     NULL,
    [NUM_DOC2]          VARCHAR (20)    NULL,
    [FLAG_NIN_INTER]    CHAR (1)        NULL,
    [FLAG_DISTRIBUIDOR] CHAR (1)        NULL,
    [FLAG_LISTA_PRECIO] CHAR (1)        NULL,
    [NUMERO_SUSPENSION] VARCHAR (20)    NULL,
    [FLAG_DSCTO]        CHAR (1)        NULL,
    [NUMERO_CUENTA1]    VARCHAR (20)    NULL,
    [COD_MONEDA1]       VARCHAR (4)     NULL,
    [UNIDADES_META]     DECIMAL (12, 2) NULL,
    [PORCENTAJE_BONO]   DECIMAL (12, 2) NULL,
    [CTA_CORREO]        VARCHAR (100)   NULL,
    [FUNES_VIGENTE]     VARCHAR (1)     NULL,
    [C_USUARIO]         CHAR (30)       NULL
);