CREATE TABLE [dbo].[articulo_planilla_bono_excluido] (
    [codigo_planilla_bono] INT             NULL,
    [codigo_canal_grupo]   INT             NULL,
    [nombre_grupo]         VARCHAR (100)   NULL,
    [codigo_personal]      INT             NULL,
    [nombre_persona]       VARCHAR (300)   NULL,
    [codigo_empresa]       INT             NULL,
    [nombre_empresa]       VARCHAR (50)    NULL,
    [codigo_canal]         INT             NULL,
    [nombre_canal]         VARCHAR (50)    NULL,
    [nombre_moneda]        VARCHAR (15)    NULL,
    [nro_contrato]         VARCHAR (100)   NULL,
    [codigo_articulo]      INT             NULL,
    [nombre_articulo]      VARCHAR (100)   NULL,
    [monto_bruto]          DECIMAL (10, 2) NULL,
    [monto_igv]            DECIMAL (10, 2) NULL,
    [monto_neto]           DECIMAL (10, 2) NULL,
    [excluido_motivo]      VARCHAR (250)   NULL,
    [excluido_usuario]     VARCHAR (100)   NULL,
    [excluido_fecha]       DATETIME        NULL,
    [dinero_ingresado]     DECIMAL (10, 2) NULL,
    [monto_contratado]     DECIMAL (10, 2) NULL,
    [porcentaje_pago]      DECIMAL (10, 2) NULL
);