CREATE TABLE [dbo].[ArticulosOFSAFinal-20171012] (
    [CCS]               NVARCHAR (255) NULL,
    [Campo Santo]       NVARCHAR (255) NULL,
    [Empresa]           NVARCHAR (255) NULL,
    [Estado]            NVARCHAR (255) NULL,
    [SKU]               NVARCHAR (255) NULL,
    [SKU_2]             NVARCHAR (255) NULL,
    [Descripción]       NVARCHAR (255) NULL,
    [Abreviatura]       NVARCHAR (255) NULL,
    [CC]                NVARCHAR (255) NULL,
    [Categoría]         NVARCHAR (255) NULL,
    [CUN]               FLOAT (53)     NULL,
    [Unidad de negocio] NVARCHAR (255) NULL,
    [CP]                FLOAT (53)     NULL,
    [Tipo de venta]     NVARCHAR (255) NULL,
    [Precio]            MONEY          NULL,
    [CON IGV]           MONEY          NULL,
    [Moneda]            NVARCHAR (255) NULL,
    [Comisión]          MONEY          NULL,
    [F19]               NVARCHAR (255) NULL,
    [F20]               NVARCHAR (255) NULL
);