CREATE TABLE [dbo].[cabecera_contrato] (
    [Codigo_empresa]             NVARCHAR (4)    NOT NULL,
    [NumAtCard]                  NVARCHAR (100)  NOT NULL,
    [CardCode]                   NVARCHAR (15)   NOT NULL,
    [CardName]                   NVARCHAR (100)  NOT NULL,
    [DocCur]                     NVARCHAR (6)    NOT NULL,
    [DocRate]                    NUMERIC (19, 6) NULL,
    [DocTotal]                   NUMERIC (19, 6) NOT NULL,
    [DocTotalFC]                 NUMERIC (19, 6) NULL,
    [Num_Importe_Igv]            NUMERIC (19, 6) NOT NULL,
    [Num_Total_Sin_Igv]          NUMERIC (19, 6) NOT NULL,
    [UpdateDate]                 DATETIME        NULL,
    [CreateDate]                 DATETIME        NOT NULL,
    [LicTradNum]                 NVARCHAR (32)   NOT NULL,
    [Cod_Tipo_Venta]             NVARCHAR (10)   NOT NULL,
    [Cod_Convenio]               NVARCHAR (20)   NULL,
    [Cod_Vendedor]               NVARCHAR (10)   NOT NULL,
    [Cod_Supervisor]             NVARCHAR (10)   NULL,
    [Cod_FormaPago]              NVARCHAR (10)   NOT NULL,
    [Flg_Documentacion_Completa] CHAR (2)        NOT NULL,
    [Flg_Recupero]               BIT             NOT NULL,
    [Monto_Recupero]             NUMERIC (19, 6) NULL,
    [Num_Contrato_Referencia]    NVARCHAR (100)  NULL,
    [Cod_Empresa_Referencia]     NVARCHAR (4)    NULL,
    [Cod_Estado_Contrato]        NVARCHAR (4)    NULL,
    [Num_Ventas]                 NUMERIC (19, 6) NULL,
    [COD_BIEN]                   NVARCHAR (6)    NULL,
    [NUM_EXPEDIENTE]             NVARCHAR (10)   NULL,
    [FLAG_TRASLADO]              NVARCHAR (1)    NULL,
    [FLAG_TIPO_ORIGEN]           NVARCHAR (1)    NULL,
    [COD_CEME_DESTINO]           NVARCHAR (4)    NULL,
    [COD_CEME_ORIGEN]            NVARCHAR (4)    NULL,
    [IMPORTE_DESCUENTO]          DECIMAL (10, 2) NULL,
    [TOTAL_CONTRATO]             DECIMAL (10, 2) NULL,
    [COD_MONEDA]                 NVARCHAR (2)    NULL,
    [OBSERV_CARGO]               NVARCHAR (100)  NULL,
    [COD_INSTITUCION]            NVARCHAR (4)    NULL,
    [DES_PROMOCION]              NVARCHAR (100)  NULL,
    [FLAG_DESGRAVAMEN]           NVARCHAR (1)    NULL,
    [FEC_FIN_SEGURO]             DATE            NULL,
    [C_AGENTE]                   NVARCHAR (10)   NULL,
    [COD_GRUPO_VENTA_G]          NVARCHAR (4)    NULL,
    [TIPO_AGENTE_G]              NVARCHAR (4)    NULL,
    [C_SUPERVISOR]               NVARCHAR (10)   NULL,
    [C_AGENCIA]                  NVARCHAR (10)   NULL,
    [NUM_CONT_REF]               NVARCHAR (10)   NULL,
    [FEC_MODI]                   DATETIME        NULL,
    [COD_USUARIO]                NVARCHAR (10)   NULL,
    [C_MOTIVO]                   NVARCHAR (4)    NULL,
    [FLAG_IMPRESION]             NVARCHAR (1)    NULL,
    [FLAG_PROCESO]               NVARCHAR (1)    NULL,
    [TIPO_TRAB]                  NVARCHAR (4)    NULL,
    [COD_EMPRESA_REF]            NVARCHAR (4)    NULL,
    [C_AGENCIA_VENDEDOR]         NVARCHAR (10)   NULL,
    [C_AGRUP_AGENTE]             NVARCHAR (1)    NULL,
    [FEC_RESCINDIDO]             DATE            NULL,
    [ESTADO_RESCINDIDO]          NVARCHAR (4)    NULL,
    [NUM_MEMO]                   NVARCHAR (10)   NULL,
    [OBSERV_RESCINDIDO]          NVARCHAR (100)  NULL,
    [NUM_ANTIGUO]                NVARCHAR (10)   NULL,
    [FLAG_COMI_ESP]              NVARCHAR (1)    NULL,
    [C_AGENCIA_SF]               NVARCHAR (10)   NULL,
    [C_MOTIVO_RESCISION]         NVARCHAR (4)    NULL,
    [NUM_CONT_CAR]               NVARCHAR (10)   NULL,
    [NUM_COMPROMISO]             NVARCHAR (10)   NULL,
    [PATERNO_APODERADO]          NVARCHAR (100)  NULL,
    [MATERNO_APODERADO]          NVARCHAR (100)  NULL,
    [NOMBRES_APODERADO]          NVARCHAR (50)   NULL,
    [DIREC_COB_APODERADO]        NVARCHAR (100)  NULL,
    [C_COD_POSTAL_D]             NVARCHAR (5)    NULL,
    [TELEFONO]                   NVARCHAR (30)   NULL,
    [CELULAR]                    NVARCHAR (30)   NULL,
    [OTRO_FONO]                  NVARCHAR (30)   NULL,
    [FLAG_DISTRIBUIDOR]          NVARCHAR (1)    NULL,
    [FLAG_LISTA_PRECIO]          NVARCHAR (1)    NULL,
    [FECHA_CARTA_RESCISION]      DATE            NULL,
    [SUSCRITA]                   NVARCHAR (100)  NULL,
    [MONTO_LIQUIDACION]          DECIMAL (10, 2) NULL,
    [VARIOS_BIENES]              NVARCHAR (1)    NULL,
    [MULTIPLES_BIENES]           NVARCHAR (1)    NULL,
    [NUM_COMPROMISO_ADI]         NVARCHAR (11)   NULL,
    [C_CONDICION]                NVARCHAR (6)    NULL,
    [C_SEGURO]                   NVARCHAR (4)    NULL,
    [C_AGENTE_ADM]               NVARCHAR (10)   NULL,
    [TIPO_AGENTE_G_ADM]          NVARCHAR (4)    NULL,
    [FLAG_INCLUYE_ESPACIO]       NVARCHAR (1)    NULL,
    [FLAG_CONVERTIDO]            NVARCHAR (1)    NULL,
    [NUM_CONT_CONVERSION]        NVARCHAR (10)   NULL,
    [USU_RESCISION]              NVARCHAR (10)   NULL,
    [FEC_USU_RESCISION]          DATETIME        NULL,
    [C_USUARIO_RESCISION]        NVARCHAR (10)   NULL,
    [COD_ESPACIO]                NVARCHAR (20)   NULL,
    [FLAG_FACTURACIONMANUAL]     NVARCHAR (1)    NULL,
    [OBSERVACIONFACTURA]         TEXT            NULL,
    [FLAG_NOBONO]                NVARCHAR (1)    NULL,
    [C_CONVENIO]                 NVARCHAR (4)    NULL,
    [FLAG_NOINFOCORP]            NVARCHAR (1)    NULL,
    [NUMEROPRINCIPALES]          INT             NULL,
    [TIPOVENTAREAL]              NVARCHAR (1)    NULL,
    [FLAG_COMPROMISO]            NVARCHAR (1)    NULL,
    [C_LISTAPRECIO]              NVARCHAR (3)    NULL,
    [C_COMPROMISOPAGO]           NVARCHAR (10)   NULL,
    [FLAG_PLANINTEGRAL]          NVARCHAR (1)    NULL,
    [OBSERVACIONES]              TEXT            NULL,
    [FLAG_LAMPARARECORDATORIA]   NVARCHAR (1)    NULL,
    [FLAG_ESPACIO]               NVARCHAR (1)    NULL,
    [FLAG_INHUMACION]            NVARCHAR (1)    NULL,
    [FLAG_PROCESADO]             NVARCHAR (1)    NULL,
    [FLAG_CONVERSION]            NVARCHAR (1)    NULL,
    [FECHADOCCOMPLETA]           DATE            NULL,
    [C_USUARIODOCCOMPLETA]       NVARCHAR (10)   NULL,
    [AUTOMATICO]                 NVARCHAR (20)   NULL,
    [TIPO_CONVENIO]              NVARCHAR (1)    NULL,
    [PERSONA1_DOC]               NVARCHAR (200)  NULL,
    [PERSONA2_DOC]               NVARCHAR (200)  NULL,
    [PARENTESCO1]                NVARCHAR (20)   NULL,
    [PARENTESCO2]                NVARCHAR (20)   NULL,
    [C_USUARIO_MANT]             NVARCHAR (18)   NULL,
    [FLAG_PAGO_MANT]             NVARCHAR (1)    NULL,
    [TIPO_VENTA_CIERRE]          NVARCHAR (1)    NULL,
    [ESTPEN_AFP]                 NVARCHAR (1)    NULL,
    [ESTPEN_ESSALUD]             NVARCHAR (1)    NULL,
    [ESTPEN_SEGURO]              NVARCHAR (1)    NULL,
    [ESTPEN_CONTRATOS]           NVARCHAR (1)    NULL,
    [CODEST]                     NVARCHAR (2)    NULL,
    [ESTPEN_RECIBODS]            NVARCHAR (1)    NULL,
    [NOTA1]                      TEXT            NULL,
    [NOTA2]                      TEXT            NULL,
    [NOTA3]                      TEXT            NULL,
    [NOTA4]                      TEXT            NULL,
    [NOTA5]                      TEXT            NULL,
    [FECHAOBS]                   DATE            NULL,
    [ELECCION_ESPACIO_COMISION]  NVARCHAR (1)    NULL,
    [Flg_Transferencia]          BIT             DEFAULT ((0)) NOT NULL,
    [DocEntry]                   INT             NULL,
    [EmpresaTransferencia]       VARCHAR (4)     NULL,
    [ContratoTransferencia]      VARCHAR (50)    NULL,
    [MontoTransferencia]         DECIMAL (18, 2) NULL,
    [FlagAdicional]              BIT             CONSTRAINT [DF_cabecera_contrato_FlagAdicional] DEFAULT ((0)) NOT NULL,
    [codigo_grupo]               VARCHAR (60)    NULL,
    [Address]                    VARCHAR (500)   NULL,
    CONSTRAINT [PK_cabecera_contrato] PRIMARY KEY CLUSTERED ([Codigo_empresa] ASC, [NumAtCard] ASC)
);