CREATE TABLE [dbo].[comision_manual] (
    [codigo_comision_manual]    INT             IDENTITY (1, 1) NOT NULL,
    [codigo_estado_cuota]       INT             NOT NULL,
    [codigo_tipo_documento]     INT             NOT NULL,
    [nro_documento]             VARCHAR (15)    NOT NULL,
    [nombre]                    VARCHAR (50)    NOT NULL,
    [apellido_paterno]          VARCHAR (50)    NOT NULL,
    [apellido_materno]          VARCHAR (50)    NOT NULL,
    [codigo_personal]           INT             NOT NULL,
    [codigo_canal]              INT             NOT NULL,
    [codigo_empresa]            INT             NULL,
    [nro_contrato]              VARCHAR (100)   NULL,
    [codigo_campo_santo]        INT             NULL,
    [codigo_articulo]           INT             NOT NULL,
    [comentario]                VARCHAR (100)   NULL,
    [codigo_tipo_venta]         INT             NOT NULL,
    [codigo_tipo_pago]          INT             NOT NULL,
    [comision_sin_igv]          DECIMAL (10, 2) NOT NULL,
    [igv]                       DECIMAL (10, 2) NOT NULL,
    [comision]                  DECIMAL (10, 2) NOT NULL,
    [codigo_planilla]           INT             NULL,
    [codigo_estado_proceso]     INT             NOT NULL,
    [estado_registro]           BIT             NOT NULL,
    [fecha_registra]            DATETIME        NOT NULL,
    [usuario_registra]          VARCHAR (50)    NOT NULL,
    [fecha_modifica]            DATETIME        NULL,
    [usuario_modifica]          VARCHAR (50)    NULL,
    [codigo_detalle_cronograma] INT             NULL,
    [en_planilla]               BIT             DEFAULT ((0)) NOT NULL,
    [nro_factura_vendedor]      VARCHAR (20)    NULL,
    CONSTRAINT [PK_comision_manual] PRIMARY KEY CLUSTERED ([codigo_comision_manual] ASC),
    CONSTRAINT [FK_comision_manual_codigo_articulo_articulo_codigo_articulo] FOREIGN KEY ([codigo_articulo]) REFERENCES [dbo].[articulo] ([codigo_articulo]),
    CONSTRAINT [FK_comision_manual_codigo_estado_cuenta_estado_cuota_codigo_estado_cuota] FOREIGN KEY ([codigo_estado_cuota]) REFERENCES [dbo].[estado_cuota] ([codigo_estado_cuota]),
    CONSTRAINT [FK_comision_manual_codigo_estado_proceso_estado_proceso_codigo_estado_proceso] FOREIGN KEY ([codigo_estado_proceso]) REFERENCES [dbo].[estado_proceso] ([codigo_estado_proceso]),
    CONSTRAINT [FK_comision_manual_codigo_tipo_documento_tipo_documento_codigo_tipo_documento] FOREIGN KEY ([codigo_tipo_documento]) REFERENCES [dbo].[tipo_documento] ([codigo_tipo_documento]),
    CONSTRAINT [FK_comision_manual_codigo_tipo_pago_tipo_pago_codigo_tipo_pago] FOREIGN KEY ([codigo_tipo_pago]) REFERENCES [dbo].[tipo_pago] ([codigo_tipo_pago]),
    CONSTRAINT [FK_comision_manual_codigo_tipo_venta_tipo_venta_codigo_tipo_venta] FOREIGN KEY ([codigo_tipo_venta]) REFERENCES [dbo].[tipo_venta] ([codigo_tipo_venta])
);