CREATE TABLE [dbo].[COMI_PLANILLAS] (
    [FEC_PLANILLA] DATETIME        NOT NULL,
    [USU_PLANILLA] VARCHAR (10)    NOT NULL,
    [FEC_INICIO]   DATETIME        NULL,
    [FEC_TERMINO]  DATETIME        NULL,
    [FEC_CIERRE]   DATETIME        NULL,
    [TIPO_CAMBIO]  DECIMAL (10, 3) NULL,
    [TIPO_MONEDA]  CHAR (1)        NULL,
    CONSTRAINT [COMI_PLANILLAS_x] PRIMARY KEY NONCLUSTERED ([FEC_PLANILLA] ASC, [USU_PLANILLA] ASC)
);