CREATE TABLE [dbo].[contrato_db2_backup] (
    [COD_EMPRESA_G]             CHAR (4)        NOT NULL,
    [NUM_CONTRATO]              VARCHAR (10)    NOT NULL,
    [COD_BIEN]                  VARCHAR (6)     NULL,
    [NUM_EXPEDIENTE]            VARCHAR (10)    NULL,
    [TIPO_VENTA]                VARCHAR (1)     NULL,
    [ID_FORMA_DE_PAGO]          VARCHAR (1)     NULL,
    [FEC_CONTRATO]              DATETIME        NULL,
    [FLAG_TRASLADO]             VARCHAR (1)     NULL,
    [FLAG_TIPO_ORIGEN]          VARCHAR (1)     NULL,
    [COD_CEME_DESTINO]          VARCHAR (4)     NULL,
    [COD_CEME_ORIGEN]           VARCHAR (4)     NULL,
    [IMPORTE_DESCUENTO]         DECIMAL (10, 3) NULL,
    [TOTAL_CONTRATO]            DECIMAL (10, 3) NULL,
    [COD_MONEDA]                VARCHAR (2)     NULL,
    [OBSERV_CARGO]              VARCHAR (100)   NULL,
    [COD_INSTITUCION]           VARCHAR (4)     NULL,
    [DES_PROMOCION]             VARCHAR (100)   NULL,
    [FLAG_DESGRAVAMEN]          VARCHAR (1)     NULL,
    [FEC_FIN_SEGURO]            DATETIME        NULL,
    [C_AGENTE]                  VARCHAR (10)    NULL,
    [COD_GRUPO_VENTA_G]         VARCHAR (4)     NULL,
    [TIPO_AGENTE_G]             VARCHAR (4)     NULL,
    [C_SUPERVISOR]              VARCHAR (10)    NULL,
    [C_AGENCIA]                 VARCHAR (10)    NULL,
    [NUM_CONT_REF]              VARCHAR (10)    NULL,
    [FEC_MODI]                  DATETIME        NULL,
    [COD_USUARIO]               VARCHAR (10)    NULL,
    [C_MOTIVO]                  CHAR (4)        NULL,
    [FLAG_IMPRESION]            CHAR (1)        NULL,
    [FLAG_PROCESO]              CHAR (1)        NULL,
    [TIPO_TRAB]                 VARCHAR (4)     NULL,
    [COD_EMPRESA_REF]           CHAR (4)        NULL,
    [C_AGENCIA_VENDEDOR]        VARCHAR (10)    NULL,
    [C_AGRUP_AGENTE]            CHAR (1)        NULL,
    [FEC_RESINDIDO]             DATETIME        NULL,
    [ESTADO_RESINDIDO]          VARCHAR (4)     NULL,
    [NUM_MEMO]                  VARCHAR (10)    NULL,
    [OBSERV_RESINDIDO]          VARCHAR (100)   NULL,
    [NUM_ANTIGUO]               VARCHAR (10)    NULL,
    [FLAG_COMI_ESP]             CHAR (1)        NULL,
    [C_AGENCIA_SF]              VARCHAR (10)    NULL,
    [C_MOTIVO_RESCISION]        CHAR (4)        NULL,
    [NUM_CONT_CAR]              VARCHAR (10)    NULL,
    [NUM_COMPROMISO]            VARCHAR (10)    NULL,
    [PATERNO_APODERADO]         VARCHAR (100)   NULL,
    [MATERNO_APODERADO]         VARCHAR (100)   NULL,
    [NOMBRES_APODERADO]         VARCHAR (50)    NULL,
    [DIREC_COB_APODERADO]       VARCHAR (100)   NULL,
    [C_COD_POSTAL_D]            VARCHAR (5)     NULL,
    [TELEFONO]                  VARCHAR (30)    NULL,
    [CELULAR]                   VARCHAR (30)    NULL,
    [OTRO_FONO]                 VARCHAR (30)    NULL,
    [FLAG_DISTRIBUIDOR]         CHAR (1)        NULL,
    [FLAG_LISTA_PRECIO]         CHAR (1)        NULL,
    [FECHA_CARTA_RESCISION]     DATETIME        NULL,
    [SUSCRITA]                  VARCHAR (100)   NULL,
    [MONTO_LIQUIDACION]         DECIMAL (15, 3) NULL,
    [VARIOS_BIENES]             CHAR (1)        NULL,
    [MULTIPLES_BIENES]          CHAR (1)        NULL,
    [NUM_COMPROMISO_ADI]        VARCHAR (11)    NULL,
    [C_CONDICION]               VARCHAR (6)     NULL,
    [C_SEGURO]                  VARCHAR (4)     NULL,
    [C_AGENTE_ADM]              VARCHAR (10)    NULL,
    [TIPO_AGENTE_G_ADM]         VARCHAR (4)     NULL,
    [FLAG_INCLUYE_ESPACIO]      CHAR (1)        NULL,
    [FLAG_CONVERTIDO]           CHAR (1)        NULL,
    [NUM_CONT_CONVERSION]       VARCHAR (10)    NULL,
    [USU_RESCISION]             VARCHAR (10)    NULL,
    [FEC_USU_RESCISION]         DATETIME        NULL,
    [C_USUARIO_RESCISION]       VARCHAR (10)    NULL,
    [COD_ESPACIO]               VARCHAR (20)    NULL,
    [FLAG_FACTURACIONMANUAL]    CHAR (1)        NULL,
    [OBSERVACIONFACTURA]        TEXT            NULL,
    [FLAG_NOBONO]               CHAR (1)        NULL,
    [C_CONVENIO]                VARCHAR (4)     NULL,
    [FLAG_NOINFOCORP]           CHAR (1)        NULL,
    [NUMEROPRINCIPALES]         INT             NULL,
    [TIPOVENTAREAL]             VARCHAR (1)     NULL,
    [FLAG_COMPROMISO]           CHAR (1)        NULL,
    [C_LISTAPRECIO]             VARCHAR (3)     NULL,
    [C_COMPROMISOPAGO]          VARCHAR (10)    NULL,
    [FLAG_PLANINTEGRAL]         CHAR (1)        NULL,
    [OBSERVACIONES]             TEXT            NULL,
    [FLAG_LAMPARARECORDATORIA]  CHAR (1)        NULL,
    [FLAG_ESPACIO]              VARCHAR (1)     NULL,
    [FLAG_INHUMACION]           CHAR (1)        NULL,
    [FLAG_PROCESADO]            CHAR (1)        NULL,
    [FLAG_CONVERSION]           CHAR (1)        NULL,
    [FLAG_DOCPENDIENTE]         CHAR (1)        NULL,
    [FLAG_DOCCOMPLETA]          CHAR (1)        NULL,
    [FECHADOCCOMPLETA]          DATETIME        NULL,
    [C_USUARIODOCCOMPLETA]      VARCHAR (10)    NULL,
    [AUTOMATICO]                VARCHAR (20)    NULL,
    [TIPO_CONVENIO]             CHAR (1)        NULL,
    [PERSONA1_DOC]              VARCHAR (200)   NULL,
    [PERSONA2_DOC]              VARCHAR (200)   NULL,
    [PARENTESCO1]               VARCHAR (20)    NULL,
    [PARENTESCO2]               VARCHAR (20)    NULL,
    [C_USUARIO_MANT]            CHAR (18)       NULL,
    [FLAG_PAGO_MANT]            CHAR (1)        NULL,
    [TIPO_VENTA_CIERRE]         VARCHAR (1)     NULL,
    [ESTPEN_AFP]                VARCHAR (1)     NULL,
    [ESTPEN_ESSALUD]            VARCHAR (1)     NULL,
    [ESTPEN_SEGURO]             VARCHAR (1)     NULL,
    [ESTPEN_CONTRATOS]          VARCHAR (1)     NULL,
    [CODEST]                    VARCHAR (2)     NULL,
    [ESTPEN_RECIBODS]           VARCHAR (1)     NULL,
    [NOTA1]                     TEXT            NULL,
    [NOTA2]                     TEXT            NULL,
    [NOTA3]                     TEXT            NULL,
    [NOTA4]                     TEXT            NULL,
    [NOTA5]                     TEXT            NULL,
    [FECHAOBS]                  DATETIME        NULL,
    [ELECCION_ESPACIO_COMISION] VARCHAR (1)     NULL,
    CONSTRAINT [CONTRATO_KEY] PRIMARY KEY NONCLUSTERED ([COD_EMPRESA_G] ASC, [NUM_CONTRATO] ASC)
);