CREATE TABLE [dbo].[conversion_espacio] (
    [codigo_conversion_espacio]       INT            IDENTITY (1, 1) NOT NULL,
    [fecha_exhumacion]                DATETIME       NULL,
    [codigo_tipo_conversion_espacio]  INT            NULL,
    [numero_informe_exhumacion]       NVARCHAR (30)  NULL,
    [observacion_exhumacion]          NVARCHAR (200) NULL,
    [fecha_inicio_encofrado]          DATETIME       NULL,
    [numero_orden_encofrado]          NVARCHAR (30)  NULL,
    [observacion_encofrado]           NVARCHAR (200) NULL,
    [fecha_inhumacion]                DATETIME       NULL,
    [numero_orden_inhumacion]         NVARCHAR (30)  NULL,
    [observacion_inhumacion]          NVARCHAR (200) NULL,
    [fecha_final_ejecucion]           DATETIME       NULL,
    [numero_orden_ejecucion]          NVARCHAR (30)  NULL,
    [observacion_ejecucion]           NVARCHAR (200) NULL,
    [estado_registro]                 BIT            DEFAULT ((1)) NOT NULL,
    [fecha_registra]                  DATETIME       DEFAULT (getdate()) NOT NULL,
    [usuario_registra]                VARCHAR (30)   NOT NULL,
    [fecha_modifica]                  DATETIME       NULL,
    [usuario_modifica]                VARCHAR (30)   NULL,
    [fecha_exhumacion_final]          DATE           NULL,
    [fecha_encofrado_fin]             DATE           NULL,
    [fecha_inhumacion_fin]            DATE           NULL,
    [fecha_inicio_conversion]         DATE           NOT NULL,
    [fecha_fin_conversion]            DATE           NULL,
    [observacion_conversion]          VARCHAR (200)  NULL,
    [nro_informe_conversion]          VARCHAR (200)  NULL,
    [codigo_espacio]                  VARCHAR (20)   NOT NULL,
    [codigo_estado_conversion_actual] INT            NULL,
    CONSTRAINT [codigo_conversion_espacio] PRIMARY KEY CLUSTERED ([codigo_conversion_espacio] ASC),
    CONSTRAINT [conversion_espacio_espacio_fk] FOREIGN KEY ([codigo_espacio]) REFERENCES [dbo].[espacio] ([codigo_espacio]),
    CONSTRAINT [conversion_espacio_estado_conversion_fk] FOREIGN KEY ([codigo_estado_conversion_actual]) REFERENCES [dbo].[estado_conversion] ([codigo_estado_conversion]),
    CONSTRAINT [conversion_espacio_tipo_conversion_fk] FOREIGN KEY ([codigo_tipo_conversion_espacio]) REFERENCES [dbo].[tipo_conversion_espacio] ([codigo_tipo_conversion_espacio])
);