CREATE TABLE [dbo].[d_contrato_db2_] (
    [NUM_CORR_CONTRATO]    VARCHAR (10)    NOT NULL,
    [COD_EMPRESA_G]        CHAR (4)        NULL,
    [NUM_CONTRATO]         VARCHAR (10)    NULL,
    [COD_BIEN]             VARCHAR (6)     NOT NULL,
    [NUM_CORR_PROD]        INT             NULL,
    [COD_CONCEPTO]         VARCHAR (3)     NOT NULL,
    [COD_ADENDO]           VARCHAR (10)    NULL,
    [CANT_PED]             INT             NULL,
    [CANT_USADO]           INT             NULL,
    [PRECIO_D_BIEN]        DECIMAL (10, 3) NULL,
    [IGV]                  DECIMAL (10, 3) NULL,
    [VALOR_VENTA]          DECIMAL (10, 3) NULL,
    [COD_MONEDA]           VARCHAR (2)     NULL,
    [TIPO_CAMBIO]          DECIMAL (10, 3) NULL,
    [FEC_MODI]             DATETIME        NULL,
    [COD_USUARIO]          VARCHAR (10)    NULL,
    [TIPO_CONCEPTO]        VARCHAR (1)     NULL,
    [FEC_ANULACION]        DATETIME        NULL,
    [A_CUENTA]             DECIMAL (10, 3) NULL,
    [VALOR_PUNTOS]         DECIMAL (10, 3) NULL,
    [FEC_CANON]            DATETIME        NULL,
    [TIPO_VENTA]           CHAR (1)        NULL,
    [ID_FORMA_DE_PAGO]     CHAR (1)        NULL,
    [DESCUENTO]            DECIMAL (10, 3) NULL,
    [PUNTOS_SUP]           DECIMAL (10, 3) NULL,
    [CUOTA_INICIAL]        DECIMAL (10, 3) NULL,
    [NUM_CONT_CAR]         VARCHAR (10)    NULL,
    [NUM_MEMO]             VARCHAR (20)    NULL,
    [PRECIO_ORIGINAL]      DECIMAL (10, 3) NULL,
    [NUM_COMPROMISO]       CHAR (10)       NULL,
    [FLAG_USADO]           CHAR (1)        NULL,
    [C_UNIDADNEGOCIO]      VARCHAR (4)     NULL,
    [C_ADICIONAL]          VARCHAR (11)    NULL,
    [FLAG_CARENCIA]        CHAR (1)        NULL,
    [VALORSUGERIDO]        FLOAT (53)      NULL,
    [TIPOVALORSUGERIDO]    CHAR (1)        NULL,
    [C_USUARIO_ANULA]      VARCHAR (10)    NULL,
    [OBSERV_CONCEP]        VARCHAR (4)     NULL,
    [ESTADO_CONCEP]        VARCHAR (1)     NULL,
    [COD_EMPRESA_G_ORIGEN] VARCHAR (4)     NULL,
    [OBSANULACONCEPTO]     VARCHAR (100)   NULL,
    [AUTOMATICO]           VARCHAR (1)     NULL,
    [C_CUOTAADMIN]         VARCHAR (11)    NULL,
    [TIPO_AGENTE_COMI]     VARCHAR (4)     NULL,
    [COD_AGENTE_COMI]      VARCHAR (10)    NULL,
    [COD_GRUPO_COMI]       VARCHAR (4)     NULL,
    [COD_SUP_COMI]         VARCHAR (10)    NULL,
    [COD_AGENCIA_COMI]     VARCHAR (10)    NULL,
    [COD_AGENCIA_VEND]     VARCHAR (10)    NULL,
    [COD_AGENCIA_SF]       VARCHAR (10)    NULL,
    [FLAG_ASF]             CHAR (1)        NULL,
    [PRECIO_S_BIEN]        DECIMAL (10, 3) NULL,
    [PDESCUENTO]           DECIMAL (10, 3) NULL,
    [FLAG_SIN_IGV]         CHAR (1)        NULL,
    [ELECC_ESPACIO_COMI]   VARCHAR (1)     NULL
);