CREATE TABLE [dbo].[detalle_contrato] (
    [Codigo_empresa]       NVARCHAR (4)    NOT NULL,
    [NumAtCard]            NVARCHAR (100)  NOT NULL,
    [Codigo_Camposanto]    NVARCHAR (4)    NOT NULL,
    [LineNum]              INT             NOT NULL,
    [ItemCode]             NVARCHAR (20)   NOT NULL,
    [Quantity]             NUMERIC (19, 6) NOT NULL,
    [Price]                NUMERIC (19, 6) NULL,
    [Flag_Adicion]         BIT             NOT NULL,
    [Valor_Promocion]      INT             DEFAULT ((0)) NOT NULL,
    [COD_BIEN]             NVARCHAR (6)    NULL,
    [NUM_CORR_PROD]        INT             NULL,
    [COD_CONCEPTO]         NVARCHAR (3)    NULL,
    [COD_ADENDO]           NVARCHAR (10)   NULL,
    [CANT_PED]             INT             NULL,
    [CANT_USADO]           INT             NULL,
    [PRECIO_D_BIEN]        DECIMAL (10, 2) NULL,
    [IGV]                  DECIMAL (10, 2) NULL,
    [VALOR_VENTA]          DECIMAL (10, 2) NULL,
    [COD_MONEDA]           NVARCHAR (2)    NULL,
    [TIPO_CAMBIO]          DECIMAL (10, 2) NULL,
    [FEC_MODI]             DATE            NULL,
    [COD_USUARIO]          NVARCHAR (10)   NULL,
    [TIPO_CONCEPTO]        NVARCHAR (1)    NULL,
    [FEC_ANULACION]        DATE            NULL,
    [A_CUENTA]             DECIMAL (10, 2) NULL,
    [VALOR_PUNTOS]         DECIMAL (10, 2) NULL,
    [FEC_CANON]            DATE            NULL,
    [TIPO_VENTA]           NVARCHAR (1)    NULL,
    [ID_FORMA_DE_PAGO]     NVARCHAR (1)    NULL,
    [DESCUENTO]            DECIMAL (10, 2) NULL,
    [PUNTOS_SUP]           DECIMAL (10, 2) NULL,
    [CUOTA_INICIAL]        DECIMAL (10, 2) NULL,
    [NUM_CONT_CAR]         NVARCHAR (10)   NULL,
    [NUM_MEMO]             NVARCHAR (20)   NULL,
    [PRECIO_ORIGINAL]      DECIMAL (10, 2) NULL,
    [NUM_COMPROMISO]       NVARCHAR (10)   NULL,
    [FLAG_USADO]           NVARCHAR (1)    NULL,
    [C_UNIDADNEGOCIO]      NVARCHAR (4)    NULL,
    [C_ADICIONAL]          NVARCHAR (11)   NULL,
    [FLAG_CARENCIA]        NVARCHAR (1)    NULL,
    [VALORSUGERIDO]        DECIMAL (10, 2) NULL,
    [TIPOVALORSUGERIDO]    NVARCHAR (1)    NULL,
    [C_USUARIO_ANULA]      NVARCHAR (10)   NULL,
    [OBSERV_CONCEP]        NVARCHAR (4)    NULL,
    [ESTADO_CONCEP]        NVARCHAR (1)    NULL,
    [COD_EMPRESA_G_ORIGEN] NVARCHAR (4)    NULL,
    [OBSANULACONCEPTO]     NVARCHAR (100)  NULL,
    [AUTOMATICO]           NVARCHAR (1)    NULL,
    [C_CUOTAADMIN]         NVARCHAR (11)   NULL,
    [TIPO_AGENTE_COMI]     NVARCHAR (4)    NULL,
    [COD_AGENTE_COMI]      NVARCHAR (10)   NULL,
    [COD_GRUPO_COMI]       NVARCHAR (4)    NULL,
    [COD_SUP_COMI]         NVARCHAR (10)   NULL,
    [COD_AGENCIA_COMI]     NVARCHAR (10)   NULL,
    [COD_AGENCIA_VEND]     NVARCHAR (10)   NULL,
    [COD_AGENCIA_SF]       NVARCHAR (10)   NULL,
    [FLAG_ASF]             NVARCHAR (1)    NULL,
    [PRECIO_S_BIEN]        DECIMAL (10, 2) NULL,
    [PDESCUENTO]           DECIMAL (10, 2) NULL,
    [FLAG_SIN_IGV]         NVARCHAR (1)    NULL,
    [ELECC_ESPACIO_COMI]   NVARCHAR (1)    NULL,
    [DocEntry]             INT             NULL,
    CONSTRAINT [PK_detalle_contrato] PRIMARY KEY CLUSTERED ([Codigo_empresa] ASC, [NumAtCard] ASC, [LineNum] ASC),
    CONSTRAINT [detalle_contrato_Codigo_empresa_NumAtCard_cabecera_contrato_Codigo_empresa_NumAtCard] FOREIGN KEY ([Codigo_empresa], [NumAtCard]) REFERENCES [dbo].[cabecera_contrato] ([Codigo_empresa], [NumAtCard])
);