CREATE TABLE [dbo].[detalle_planilla] (
    [codigo_detalle_planilla]     INT             IDENTITY (1, 1) NOT NULL,
    [codigo_planilla]             INT             NOT NULL,
    [codigo_articulo]             INT             NOT NULL,
    [codigo_canal]                INT             NOT NULL,
    [codigo_grupo]                INT             NULL,
    [codigo_empresa]              INT             NOT NULL,
    [codigo_personal]             INT             NOT NULL,
    [codigo_moneda]               INT             NOT NULL,
    [nro_contrato]                VARCHAR (200)   NOT NULL,
    [codigo_tipo_venta]           INT             NOT NULL,
    [codigo_tipo_pago]            INT             NOT NULL,
    [codigo_cronograma]           INT             NOT NULL,
    [codigo_detalle_cronograma]   INT             NOT NULL,
    [excluido]                    BIT             NOT NULL,
    [nro_cuota]                   INT             NOT NULL,
    [fecha_pago]                  DATETIME        NOT NULL,
    [monto_bruto]                 DECIMAL (10, 2) NULL,
    [igv]                         DECIMAL (10, 2) NULL,
    [monto_neto]                  DECIMAL (10, 2) NULL,
    [observacion]                 VARCHAR (250)   NULL,
    [estado_registro]             BIT             NOT NULL,
    [fecha_registra]              DATETIME        NOT NULL,
    [usuario_registra]            VARCHAR (50)    NOT NULL,
    [fecha_modifica]              DATETIME        NULL,
    [usuario_modifica]            VARCHAR (50)    NULL,
    [codigo_personal_referencial] INT             NULL,
    [es_transferencia]            BIT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_detalle_planilla] PRIMARY KEY CLUSTERED ([codigo_detalle_planilla] ASC),
    CONSTRAINT [FK_detalle_planilla_articulo] FOREIGN KEY ([codigo_articulo]) REFERENCES [dbo].[articulo] ([codigo_articulo]),
    CONSTRAINT [FK_detalle_planilla_codigo_planilla_planilla_codigo_planilla] FOREIGN KEY ([codigo_planilla]) REFERENCES [dbo].[planilla] ([codigo_planilla]),
    CONSTRAINT [FK_detalle_planilla_empresa_sigeco] FOREIGN KEY ([codigo_empresa]) REFERENCES [dbo].[empresa_sigeco] ([codigo_empresa])
);