CREATE TABLE [dbo].[espacio] (
    [codigo_espacio]             VARCHAR (20)  NOT NULL,
    [codigo_espacio_visual]      VARCHAR (20)  NOT NULL,
    [codigo_espacio_auxiliar]    VARCHAR (20)  NULL,
    [codigo_corporacion]         INT           NOT NULL,
    [codigo_empresa]             INT           NOT NULL,
    [codigo_campo_santo]         INT           NOT NULL,
    [codigo_plataforma]          INT           NOT NULL,
    [id_sector]                  INT           NOT NULL,
    [codigo_tipo_espacio]        INT           NULL,
    [codigo_tipo_nivel]          CHAR (1)      NOT NULL,
    [eje_derecho]                VARCHAR (10)  NOT NULL,
    [eje_izquierdo]              VARCHAR (10)  NOT NULL,
    [eje_superior]               VARCHAR (10)  NOT NULL,
    [eje_inferior]               VARCHAR (10)  NOT NULL,
    [codigo_plano]               VARCHAR (20)  NULL,
    [fecha_registra]             DATETIME      NOT NULL,
    [fecha_modifica]             DATETIME      NULL,
    [usuario_registra]           VARCHAR (50)  NOT NULL,
    [usuario_modifica]           VARCHAR (50)  NULL,
    [id_edificio]                INT           NULL,
    [eje_leyenda]                VARCHAR (20)  NULL,
    [es_leyenda]                 BIT           DEFAULT ((0)) NOT NULL,
    [eje_columna]                INT           NULL,
    [eje_fila]                   INT           NULL,
    [cantidad_nivel_espacio]     INT           DEFAULT ((1)) NOT NULL,
    [cantidad_nivel_ocupado]     INT           DEFAULT ((0)) NOT NULL,
    [en_conversion]              BIT           DEFAULT ((0)) NOT NULL,
    [cantidad_maxima_conversion] INT           DEFAULT ((1)) NOT NULL,
    [indica_espacio_definitivo]  BIT           DEFAULT ((1)) NOT NULL,
    [codigo_estado_espacio]      INT           NOT NULL,
    [habilitado]                 BIT           DEFAULT ((1)) NOT NULL,
    [es_nicho_tipo_yumbo]        BIT           DEFAULT ((0)) NOT NULL,
    [codigo_vista_nicho]         INT           NULL,
    [cara_nicho]                 CHAR (1)      DEFAULT (' ') NULL,
    [numero_secuencia_sector]    INT           DEFAULT ((0)) NOT NULL,
    [codigo_tipo_bien]           INT           DEFAULT ((1)) NULL,
    [codigo_piso_pabellon]       INT           NULL,
    [encofrado]                  BIT           DEFAULT ((0)) NOT NULL,
    [lapida]                     BIT           DEFAULT ((0)) NOT NULL,
    [observacion]                NVARCHAR (20) NULL,
    [numero_grupo]               VARCHAR (10)  NULL,
    CONSTRAINT [espacio_pk] PRIMARY KEY CLUSTERED ([codigo_espacio] ASC),
    FOREIGN KEY ([id_edificio]) REFERENCES [dbo].[edificio] ([id_edificio]),
    CONSTRAINT [campo_santo_espacio_fk] FOREIGN KEY ([codigo_campo_santo]) REFERENCES [dbo].[campo_santo] ([codigo_campo_santo]),
    CONSTRAINT [corporacion_espacio_fk] FOREIGN KEY ([codigo_corporacion]) REFERENCES [dbo].[corporacion] ([codigo_corporacion]),
    CONSTRAINT [empresa_espacio_fk] FOREIGN KEY ([codigo_empresa]) REFERENCES [dbo].[empresa] ([codigo_empresa]),
    CONSTRAINT [espacio__tipo_bien_fk] FOREIGN KEY ([codigo_tipo_bien]) REFERENCES [dbo].[tipo_bien] ([codigo_tipo_bien]),
    CONSTRAINT [espacio_piso_pabellon_fk] FOREIGN KEY ([codigo_piso_pabellon]) REFERENCES [dbo].[piso_pabellon] ([codigo_piso_pabellon]),
    CONSTRAINT [espacio_sector_fk] FOREIGN KEY ([id_sector]) REFERENCES [dbo].[sector] ([id_sector]),
    CONSTRAINT [espacio_vista_pabellon_fk] FOREIGN KEY ([codigo_vista_nicho]) REFERENCES [dbo].[vista_pabellon] ([codigo_vista_pabellon]),
    CONSTRAINT [plataforma_espacio_fk] FOREIGN KEY ([codigo_plataforma]) REFERENCES [dbo].[plataforma] ([codigo_plataforma]),
    CONSTRAINT [tipo_espacio_espacio_fk] FOREIGN KEY ([codigo_tipo_espacio]) REFERENCES [dbo].[tipo_espacio] ([codigo_tipo_espacio]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [tipo_nivel_espacio_fk] FOREIGN KEY ([codigo_tipo_nivel]) REFERENCES [dbo].[tipo_nivel] ([codigo_tipo_nivel]) ON DELETE CASCADE ON UPDATE CASCADE
);