CREATE TABLE [dbo].[EXPEDIENTE_DB2] (
    [NUM_EXPEDIENTE]        VARCHAR (10)    NOT NULL,
    [C_PERSONA]             VARCHAR (6)     NOT NULL,
    [FECHA_ING]             DATETIME        NULL,
    [COD_SEXO]              CHAR (1)        NULL,
    [NOMBRE]                VARCHAR (80)    NULL,
    [APELLIDO_PATERNO]      VARCHAR (40)    NULL,
    [APELLIDO_MATERNO]      VARCHAR (40)    NULL,
    [COD_DOC]               VARCHAR (4)     NULL,
    [NUM_DOC]               VARCHAR (20)    NULL,
    [FECHA_NACIMIENTO]      DATETIME        NULL,
    [COD_ESTADO_CIVIL]      CHAR (1)        NULL,
    [C_CARGO]               VARCHAR (2)     NULL,
    [DIRECCION]             VARCHAR (100)   NULL,
    [C_COD_POSTAL]          VARCHAR (5)     NULL,
    [E_MAIL]                VARCHAR (50)    NULL,
    [DIRECCION_COBRANZA]    VARCHAR (100)   NULL,
    [C_COD_POSTAL_D]        VARCHAR (5)     NULL,
    [TELEFONO]              VARCHAR (30)    NULL,
    [CELULAR]               VARCHAR (30)    NULL,
    [OTRO_FONO]             VARCHAR (30)    NULL,
    [TOTAL_COAPSA]          DECIMAL (10, 3) NULL,
    [FEC_MODI]              DATETIME        NULL,
    [COD_USUARIO]           VARCHAR (10)    NULL,
    [FLAG_NATURAL]          CHAR (1)        NULL,
    [FLAG_PROCESADO]        CHAR (1)        NULL,
    [C_USUARIO]             VARCHAR (10)    NULL,
    [FECHA_CREACION]        DATETIME        NULL,
    [FLAG_VIRTUAL]          CHAR (1)        NULL,
    [DIR_COBRANZA_NEO]      VARCHAR (180)   NULL,
    [COD_POSTAL_NEO]        VARCHAR (5)     NULL,
    [FLAG_NOENVIARCONTRATO] CHAR (1)        NULL,
    [FLAG_EMPRESA]          CHAR (1)        NULL,
    [AUTOMATICO]            VARCHAR (1)     NULL,
    CONSTRAINT [EXPEDIENTE_K] PRIMARY KEY NONCLUSTERED ([NUM_EXPEDIENTE] ASC)
);