CREATE TABLE [dbo].[lapida] (
    [codigo_lapida]          INT          IDENTITY (1, 1) NOT NULL,
    [apellido_paterno]       VARCHAR (30) NOT NULL,
    [apellido_materno]       VARCHAR (30) NULL,
    [nombres]                VARCHAR (30) NOT NULL,
    [apelativo]              VARCHAR (50) NULL,
    [texto_adicional]        VARCHAR (50) NULL,
    [fecha_nacimiento]       DATETIME     NOT NULL,
    [fecha_defuncion]        DATETIME     NOT NULL,
    [estado_registro]        BIT          DEFAULT ((1)) NOT NULL,
    [fecha_registra]         DATETIME     DEFAULT (getdate()) NOT NULL,
    [fecha_modifica]         DATETIME     NULL,
    [usuario_registra]       VARCHAR (50) NOT NULL,
    [usuario_modifica]       VARCHAR (50) NULL,
    [codigo_espacio]         VARCHAR (20) NOT NULL,
    [codigo_fallecido]       INT          NULL,
    [codigo_tipo_nivel]      CHAR (1)     NOT NULL,
    [codigo_cabecera_lapida] INT          NULL,
    CONSTRAINT [lapida_pk] PRIMARY KEY CLUSTERED ([codigo_lapida] ASC),
    FOREIGN KEY ([codigo_cabecera_lapida]) REFERENCES [dbo].[cabecera_lapida] ([codigo_cabecera_lapida]),
    CONSTRAINT [lapida_espacio_fk] FOREIGN KEY ([codigo_espacio]) REFERENCES [dbo].[espacio] ([codigo_espacio]),
    CONSTRAINT [lapida_fallecido_fk] FOREIGN KEY ([codigo_fallecido]) REFERENCES [dbo].[fallecido] ([codigo_fallecido]),
    CONSTRAINT [lapida_tipo_nivel_fk] FOREIGN KEY ([codigo_tipo_nivel]) REFERENCES [dbo].[tipo_nivel] ([codigo_tipo_nivel])
);