CREATE TABLE [dbo].[personal] (
    [codigo_personal]       INT           IDENTITY (1, 1) NOT NULL,
    [codigo_equivalencia]   NVARCHAR (10) NULL,
    [codigo_tipo_documento] INT           NOT NULL,
    [codigo_banco]          INT           NOT NULL,
    [es_persona_juridica]   BIT           NOT NULL,
    [nombre]                VARCHAR (250) NOT NULL,
    [apellido_paterno]      VARCHAR (250) NULL,
    [apellido_materno]      VARCHAR (250) NULL,
    [nro_documento]         VARCHAR (15)  NULL,
    [nro_ruc]               VARCHAR (11)  NULL,
    [telefono_fijo]         VARCHAR (10)  NULL,
    [telefono_celular]      VARCHAR (10)  NULL,
    [correo_electronico]    VARCHAR (100) NOT NULL,
    [nro_cuenta]            VARCHAR (50)  NOT NULL,
    [codigo_interbancario]  VARCHAR (50)  NULL,
    [estado_registro]       BIT           NOT NULL,
    [fecha_registra]        DATETIME      NOT NULL,
    [usuario_registra]      VARCHAR (50)  NOT NULL,
    [fecha_modifica]        DATETIME      NULL,
    [usuario_modifica]      VARCHAR (50)  NULL,
    [codigo_tipo_cuenta]    INT           NULL,
    [codigo_cuenta_moneda]  INT           NULL,
    CONSTRAINT [PK_personal] PRIMARY KEY CLUSTERED ([codigo_personal] ASC),
    CONSTRAINT [FK_personal_codigo_banco_banco_codigo_banco] FOREIGN KEY ([codigo_banco]) REFERENCES [dbo].[banco] ([codigo_banco]),
    CONSTRAINT [FK_personal_codigo_moneda_moneda_codigo_moneda] FOREIGN KEY ([codigo_cuenta_moneda]) REFERENCES [dbo].[moneda] ([codigo_moneda]),
    CONSTRAINT [FK_personal_codigo_tipo_cuenta_tipo_cuenta_codigo_tipo_cuenta] FOREIGN KEY ([codigo_tipo_cuenta]) REFERENCES [dbo].[tipo_cuenta] ([codigo_tipo_cuenta]),
    CONSTRAINT [FK_personal_codigo_tipo_documento_tipo_documento_codigo_tipo_documento] FOREIGN KEY ([codigo_tipo_documento]) REFERENCES [dbo].[tipo_documento] ([codigo_tipo_documento])
);