CREATE TABLE [dbo].[planilla] (
    [codigo_planilla]            INT           IDENTITY (1, 1) NOT NULL,
    [numero_planilla]            NVARCHAR (50) NULL,
    [fecha_anulacion]            DATETIME      NULL,
    [usuario_anulacion]          VARCHAR (50)  NULL,
    [fecha_apertura]             DATETIME      NOT NULL,
    [usuario_apertura]           VARCHAR (50)  NOT NULL,
    [fecha_cierre]               DATETIME      NULL,
    [usuario_cierre]             VARCHAR (50)  NULL,
    [fecha_inicio]               DATETIME      NOT NULL,
    [fecha_fin]                  DATETIME      NOT NULL,
    [codigo_tipo_planilla]       INT           NOT NULL,
    [codigo_estado_planilla]     INT           NOT NULL,
    [estado_registro]            BIT           NOT NULL,
    [fecha_registra]             DATETIME      NOT NULL,
    [fecha_modifica]             DATETIME      NULL,
    [usuario_registra]           VARCHAR (50)  NOT NULL,
    [usuario_modifica]           VARCHAR (50)  NULL,
    [codigo_regla_tipo_planilla] INT           NULL,
    CONSTRAINT [PK_planilla] PRIMARY KEY CLUSTERED ([codigo_planilla] ASC),
    CONSTRAINT [FK_planilla_codigo_estado_planilla_estado_planilla_codigo_estado_planilla] FOREIGN KEY ([codigo_estado_planilla]) REFERENCES [dbo].[estado_planilla] ([codigo_estado_planilla]),
    CONSTRAINT [fk_planilla_codigo_regla_tipo_planilla_regla_tipo_planilla_codigo_regla_tipo_planilla] FOREIGN KEY ([codigo_regla_tipo_planilla]) REFERENCES [dbo].[regla_tipo_planilla] ([codigo_regla_tipo_planilla]),
    CONSTRAINT [FK_planilla_codigo_tipo_planilla_tipo_planilla_codigo_tipo_planilla] FOREIGN KEY ([codigo_tipo_planilla]) REFERENCES [dbo].[tipo_planilla] ([codigo_tipo_planilla])
);