CREATE TABLE [dbo].[planilla_bono] (
    [codigo_planilla]        INT          IDENTITY (1, 1) NOT NULL,
    [numero_planilla]        VARCHAR (10) NOT NULL,
    [codigo_tipo_planilla]   INT          NULL,
    [codigo_estado_planilla] INT          NULL,
    [fecha_inicio]           DATETIME     NULL,
    [fecha_fin]              DATETIME     NULL,
    [fecha_apertura]         DATETIME     NULL,
    [fecha_anulacion]        DATETIME     NULL,
    [usuario_apertura]       VARCHAR (50) NULL,
    [usuario_anulacion]      VARCHAR (50) NULL,
    [fecha_cierre]           DATETIME     NULL,
    [usuario_cierre]         VARCHAR (50) NULL,
    [estado_registro]        BIT          NULL,
    [fecha_registra]         DATETIME     NULL,
    [usuario_registra]       VARCHAR (50) NULL,
    [fecha_modifica]         DATETIME     NULL,
    [usuario_modifica]       VARCHAR (50) NULL,
    [codigo_canal]           INT          NOT NULL,
    [es_planilla_jn]         BIT          NOT NULL,
    CONSTRAINT [PK_planilla_bono] PRIMARY KEY CLUSTERED ([codigo_planilla] ASC),
    CONSTRAINT [FK_planilla_bono_estado_planilla] FOREIGN KEY ([codigo_estado_planilla]) REFERENCES [dbo].[estado_planilla] ([codigo_estado_planilla]),
    CONSTRAINT [FK_planilla_bono_tipo_planilla] FOREIGN KEY ([codigo_tipo_planilla]) REFERENCES [dbo].[tipo_planilla] ([codigo_tipo_planilla]),
    CONSTRAINT [planilla_bono_codigo_canal_canal_grupo_codigo_canal_grupo] FOREIGN KEY ([codigo_canal]) REFERENCES [dbo].[canal_grupo] ([codigo_canal_grupo])
);