CREATE TABLE [dbo].[plataforma] (
    [codigo_plataforma]      INT          IDENTITY (1, 1) NOT NULL,
    [codigo_corporacion]     INT          NOT NULL,
    [codigo_empresa]         INT          NOT NULL,
    [codigo_campo_santo]     INT          NOT NULL,
    [nombre_plataforma]      VARCHAR (50) NOT NULL,
    [estado_registro]        BIT          NOT NULL,
    [identificador]          VARCHAR (2)  NULL,
    [codigo_tipo_plataforma] INT          NOT NULL,
    [codigo_tipo_espacio]    INT          NULL,
    [numero_columnas]        INT          NOT NULL,
    [numero_filas]           INT          NOT NULL,
    [cantidad_pisos_sector]  INT          DEFAULT ((0)) NULL,
    [fecha_registra]         DATETIME     NOT NULL,
    [fecha_modifica]         DATETIME     NULL,
    [usuario_registra]       VARCHAR (50) NOT NULL,
    [usuario_modifica]       VARCHAR (50) NULL,
    [tiene_piso]             BIT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [plataforma_pk] PRIMARY KEY CLUSTERED ([codigo_plataforma] ASC),
    FOREIGN KEY ([codigo_tipo_espacio]) REFERENCES [dbo].[tipo_espacio] ([codigo_tipo_espacio]),
    FOREIGN KEY ([codigo_tipo_plataforma]) REFERENCES [dbo].[tipo_plataforma] ([codigo_tipo_plataforma]),
    CONSTRAINT [campo_santo_plataforma_fk] FOREIGN KEY ([codigo_campo_santo]) REFERENCES [dbo].[campo_santo] ([codigo_campo_santo]),
    CONSTRAINT [corporacion_plataforma_fk] FOREIGN KEY ([codigo_corporacion]) REFERENCES [dbo].[corporacion] ([codigo_corporacion]),
    CONSTRAINT [empresa_plataforma_fk] FOREIGN KEY ([codigo_empresa]) REFERENCES [dbo].[empresa] ([codigo_empresa])
);