CREATE TABLE [dbo].[precio_articulo] (
    [codigo_precio]      INT             IDENTITY (1, 1) NOT NULL,
    [codigo_campo_santo] INT             NULL,
    [codigo_articulo]    INT             NOT NULL,
    [codigo_empresa]     INT             NOT NULL,
    [codigo_tipo_venta]  INT             NOT NULL,
    [codigo_moneda]      INT             NOT NULL,
    [precio]             DECIMAL (10, 2) NOT NULL,
    [igv]                DECIMAL (10, 2) NOT NULL,
    [precio_total]       DECIMAL (10, 2) NOT NULL,
    [vigencia_inicio]    DATETIME        NOT NULL,
    [vigencia_fin]       DATETIME        NOT NULL,
    [estado_registro]    BIT             NOT NULL,
    [fecha_registra]     DATETIME        NOT NULL,
    [usuario_registra]   VARCHAR (50)    NOT NULL,
    [fecha_modifica]     DATETIME        NULL,
    [usuario_modifica]   VARCHAR (50)    NULL,
    [cuota_inicial]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_precio_articulo] PRIMARY KEY CLUSTERED ([codigo_precio] ASC),
    CONSTRAINT [FK_precio_articulo_codigo_articulo_articulo_codigo_articulo] FOREIGN KEY ([codigo_articulo]) REFERENCES [dbo].[articulo] ([codigo_articulo]),
    CONSTRAINT [FK_precio_articulo_codigo_empresa_empresa_sigeco_codigo_empresa] FOREIGN KEY ([codigo_empresa]) REFERENCES [dbo].[empresa_sigeco] ([codigo_empresa]),
    CONSTRAINT [FK_precio_articulo_codigo_moneda_moneda_codigo_moneda] FOREIGN KEY ([codigo_moneda]) REFERENCES [dbo].[moneda] ([codigo_moneda]),
    CONSTRAINT [FK_precio_articulo_codigo_tipo_venta_tipo_venta_codigo_tipo_venta] FOREIGN KEY ([codigo_tipo_venta]) REFERENCES [dbo].[tipo_venta] ([codigo_tipo_venta])
);