CREATE TABLE [dbo].[reclamo] (
    [codigo_reclamo]             INT             IDENTITY (1, 1) NOT NULL,
    [codigo_personal]            INT             NULL,
    [nrocontrato]                VARCHAR (20)    NULL,
    [codigo_articulo]            INT             NULL,
    [codigo_empresa]             INT             NULL,
    [cuota]                      INT             NULL,
    [importe]                    DECIMAL (18, 2) NULL,
    [atencion_codigo_articulo]   INT             NULL,
    [atencion_codigo_empresa]    INT             NULL,
    [atencion_cuota]             INT             NULL,
    [atencion_importe]           DECIMAL (18, 2) NULL,
    [codigo_estado_reclamo]      INT             NULL,
    [codigo_estado_resultado]    INT             NULL,
    [observacion]                VARCHAR (1000)  NULL,
    [respuesta]                  VARCHAR (1000)  NULL,
    [codigo_planilla]            INT             NULL,
    [usuario_registra]           VARCHAR (50)    NULL,
    [fecha_registra]             DATETIME        NULL,
    [usuario_modifica]           VARCHAR (50)    NULL,
    [fecha_modifica]             DATETIME        NULL,
    [codigo_detalle_cronograma]  INT             NULL,
    [es_contrato_migrado]        BIT             DEFAULT ((0)) NOT NULL,
    [codigo_estado_resultado_n1] INT             NULL,
    [usuario_modifica_n1]        VARCHAR (50)    NULL,
    [fecha_modifica_n1]          DATETIME        NULL,
    [observacion_n1]             VARCHAR (300)   NULL,
    [codigo_estado_resultado_n2] INT             NULL,
    [usuario_modifica_n2]        VARCHAR (50)    NULL,
    [fecha_modifica_n2]          DATETIME        NULL,
    [observacion_n2]             VARCHAR (300)   NULL,
    CONSTRAINT [PK_reclamo] PRIMARY KEY CLUSTERED ([codigo_reclamo] ASC),
    CONSTRAINT [FK_reclamo_estado_reclamo] FOREIGN KEY ([codigo_estado_reclamo]) REFERENCES [dbo].[estado_reclamo] ([codigo_estado_reclamo])
);