CREATE TABLE [dbo].[regla_pago_comision] (
    [codigo_regla_pago]            INT          IDENTITY (1, 1) NOT NULL,
    [nombre_regla_pago]            VARCHAR (50) NOT NULL,
    [codigo_empresa]               INT          NULL,
    [codigo_campo_santo]           INT          NULL,
    [codigo_canal_grupo]           INT          NULL,
    [codigo_tipo_venta]            INT          NULL,
    [codigo_tipo_pago]             INT          NULL,
    [codigo_articulo]              INT          NULL,
    [tipo_pago]                    INT          DEFAULT ((0)) NOT NULL,
    [valor_inicial_pago]           VARCHAR (18) NULL,
    [valor_cuota_pago]             VARCHAR (18) NULL,
    [fecha_inicio]                 DATETIME     NULL,
    [fecha_fin]                    DATETIME     NULL,
    [estado_registro]              BIT          NULL,
    [fecha_registra]               DATETIME     NULL,
    [fecha_modifica]               DATETIME     NULL,
    [usuario_registra]             VARCHAR (50) NULL,
    [usuario_modifica]             VARCHAR (50) NULL,
    [codigo_tipo_articulo]         INT          NULL,
    [evaluar_plan_integral]        BIT          NOT NULL,
    [evaluar_anexado]              BIT          NOT NULL,
    [codigo_tipo_articulo_anexado] INT          NULL,
    [orden]                        INT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_regla_pago_comision] PRIMARY KEY CLUSTERED ([codigo_regla_pago] ASC)
);