CREATE TABLE [dbo].[sigeco_reporte_bono_detalle_supervisor] (
    [codigo_planilla]              INT             NULL,
    [fecha_inicio]                 VARCHAR (10)    NULL,
    [fecha_fin]                    VARCHAR (10)    NULL,
    [nombre_canal]                 VARCHAR (250)   NULL,
    [codigo_estado_planilla]       INT             NULL,
    [codigo_supervisor]            INT             NULL,
    [apellidos_nombres_supervisor] VARCHAR (250)   NULL,
    [codigo_empresa]               INT             NULL,
    [nombre_empresa]               VARCHAR (250)   NULL,
    [codigo_grupo]                 INT             NULL,
    [nombre_grupo]                 VARCHAR (250)   NULL,
    [monto_bruto_empresa]          DECIMAL (12, 2) NULL,
    [monto_neto_empresa]           DECIMAL (12, 2) NULL,
    [monto_detraccion_empresa]     DECIMAL (12, 2) NULL,
    [monto_neto_bono_empresa]      DECIMAL (12, 2) NULL,
    [monto_ingresado_empresa]      DECIMAL (12, 2) NULL,
    [monto_igv_empresa]            DECIMAL (12, 2) NULL,
    [monto_neto_supervisor]        DECIMAL (12, 2) NULL,
    [monto_contratado_supervisor]  DECIMAL (12, 2) NULL,
    [monto_ingresado_supervisor]   DECIMAL (12, 2) NULL,
    [codigo_personal]              INT             NULL,
    [apellidos_nombres_personal]   VARCHAR (250)   NULL,
    [numero_contrato]              VARCHAR (100)   NULL,
    [nombre_tipo_venta]            VARCHAR (50)    NULL,
    [monto_contratado]             DECIMAL (12, 2) NULL,
    [monto_ingresado]              DECIMAL (12, 2) NULL,
    [porcentaje_pago]              DECIMAL (12, 2) NULL,
    [monto_bono]                   DECIMAL (12, 2) NULL,
    [fecha_contrato]               VARCHAR (10)    NULL
);