CREATE TABLE [dbo].[sigeco_reporte_bono_liquidacion] (
    [codigo_planilla]                     INT             NULL,
    [concepto]                            VARCHAR (250)   NULL,
    [porcentaje_detraccion]               DECIMAL (12, 2) NULL,
    [fecha_inicio]                        VARCHAR (10)    NULL,
    [fecha_fin]                           VARCHAR (10)    NULL,
    [nombre_canal]                        VARCHAR (250)   NULL,
    [codigo_estado_planilla]              INT             NULL,
    [nombre_empresa_largo]                VARCHAR (250)   NULL,
    [direccion_fiscal]                    VARCHAR (250)   NULL,
    [ruc]                                 VARCHAR (50)    NULL,
    [nro_documento]                       VARCHAR (50)    NULL,
    [nombre_tipo_documento]               VARCHAR (250)   NULL,
    [codigo_supervisor]                   INT             NULL,
    [apellidos_nombres_supervisor]        VARCHAR (250)   NULL,
    [codigo_empresa]                      INT             NULL,
    [nombre_empresa]                      VARCHAR (250)   NULL,
    [codigo_grupo]                        INT             NULL,
    [nombre_grupo]                        VARCHAR (250)   NULL,
    [monto_bruto_empresa_supervisor]      DECIMAL (12, 2) NULL,
    [monto_igv_empresa_supervisor]        DECIMAL (12, 2) NULL,
    [monto_neto_empresa_supervisor]       DECIMAL (12, 2) NULL,
    [monto_detraccion_empresa_supervisor] DECIMAL (12, 2) NULL,
    [monto_neto_pagar_empresa_supervisor] DECIMAL (12, 2) NULL,
    [neto_pagar_empresa_supervisor_letra] VARCHAR (500)   NULL,
	[codigo_canal]                        INT             NULL,
	[nombre_supervisor]                   VARCHAR (250)   NULL,
	[email_supervisor]                    VARCHAR (250)   NULL
);