CREATE TABLE [dbo].[sigeco_reporte_comision_planilla] (
    [codigo_planilla]                   INT             NOT NULL,
    [codigo_tipo_planilla]              INT             NULL,
    [nombre_tipo_planilla]              VARCHAR (50)    NULL,
    [numero_planilla]                   VARCHAR (50)    NULL,
    [codigo_estado_planilla]            INT             NULL,
    [fecha_inicio]                      VARCHAR (10)    NULL,
    [fecha_fin]                         VARCHAR (10)    NULL,
    [codigo_moneda]                     INT             NULL,
    [moneda]                            VARCHAR (25)    NULL,
    [articulo]                          VARCHAR (250)   NOT NULL,
    [nro_contrato]                      VARCHAR (100)   NOT NULL,
    [nro_cuota]                         INT             NOT NULL,
    [tipo_venta]                        VARCHAR (25)    NULL,
    [tipo_pago]                         VARCHAR (25)    NULL,
    [codigo_empresa]                    INT             NOT NULL,
    [empresa]                           VARCHAR (25)    NULL,
    [codigo_canal]                      INT             NULL,
    [canal]                             VARCHAR (250)   NULL,
    [codigo_grupo]                      INT             NULL,
    [grupo]                             VARCHAR (250)   NULL,
    [codigo_personal]                   INT             NULL,
    [personal]                          VARCHAR (250)   NULL,
    [personal_referencial]              VARCHAR (250)   NULL,
    [monto_bruto]                       DECIMAL (10, 2) NULL,
    [igv]                               DECIMAL (10, 2) NULL,
    [monto_neto]                        DECIMAL (10, 2) NULL,
    [monto_bruto_empresa]               DECIMAL (10, 2) NULL,
    [igv_empresa]                       DECIMAL (10, 2) NULL,
    [monto_neto_empresa]                DECIMAL (10, 2) NULL,
    [monto_bruto_canal]                 DECIMAL (10, 2) NULL,
    [igv_canal]                         DECIMAL (10, 2) NULL,
    [monto_neto_canal]                  DECIMAL (10, 2) NULL,
    [monto_bruto_grupo]                 DECIMAL (10, 2) NULL,
    [igv_grupo]                         DECIMAL (10, 2) NULL,
    [monto_neto_grupo]                  DECIMAL (10, 2) NULL,
    [monto_bruto_personal]              DECIMAL (10, 2) NULL,
    [igv_personal]                      DECIMAL (10, 2) NULL,
    [monto_neto_personal]               DECIMAL (10, 2) NULL,
    [monto_descuento]                   DECIMAL (10, 2) NULL,
    [monto_neto_personal_con_descuento] DECIMAL (10, 2) NULL,
    [monto_detraccion_personal]         DECIMAL (10, 2) NULL,
    [monto_neto_pagar_personal]         DECIMAL (10, 2) NULL,
    [es_comision_manual]                BIT             NULL,
    [fecha_contrato]                    VARCHAR (10)    NULL,
    [usuario_cm]                        VARCHAR (50)    NULL,
    [tipo_reporte]                      VARCHAR (50)    NULL
);