USE SIGECO
GO

IF OBJECT_ID('dbo.sigeco_reporte_bono_trimestral_contabilidad', 'U') IS NOT NULL 
	DROP TABLE dbo.sigeco_reporte_bono_trimestral_contabilidad; 
GO

CREATE TABLE [dbo].[sigeco_reporte_bono_trimestral_contabilidad](
	[ORDEN] [varchar](25) NULL,
	[codigo_planilla] [int] NULL,
	[codigo_empresa] [int] NULL,
	[COD_COMISION] [varchar](25) NULL,
	[N_CUOTA] [varchar](25) NULL,
	[IMP_PAGAR] [varchar](25) NULL,
	[COD_EMPRESA_G] [varchar](25) NULL,
	[NUM_CONTRATO] [varchar](25) NULL,
	[IGV] [varchar](25) NULL,
	[DES_TIPO_VENTA] [varchar](25) NULL,
	[TIPO_VENTA] [varchar](25) NULL,
	[FEC_HAVILITADO] [varchar](25) NULL,
	[DES_FORMA_PAGO] [varchar](25) NULL,
	[ID_FORMA_DE_PAGO] [varchar](25) NULL,
	[DES_TIPO_COMISION] [varchar](25) NULL,
	[TIPO_COMISION] [varchar](25) NULL,
	[CUARTA] [varchar](25) NULL,
	[IES] [varchar](25) NULL,
	[TIPO_MONEDA] [varchar](25) NULL,
	[TIPO_AGENTE_G] [varchar](25) NULL,
	[C_AGENTE] [varchar](25) NULL,
	[COD_GRUPO_VENTA_G] [varchar](25) NULL,
	[NOMBRE_GRUPO] [varchar](250) NULL,
	[DESCRIPCION_1] [varchar](250) NULL,
	[COD_BIEN] [varchar](25) NULL,
	[DESCRIPCION_2] [varchar](250) NULL,
	[COD_CONCEPTO] [varchar](25) NULL,
	[TIPO_CAMBIO] [varchar](25) NULL,
	[SALDO_A_PAGAR] [varchar](25) NULL,
	[FEC_PLANILLA] [varchar](25) NULL,
	[USU_PLANILLA] [varchar](50) NULL,
	[N_OPERACION] [varchar](25) NULL,
	[FEC_CIERRE] [varchar](25) NULL,
	[DESC_TIPO_DOCUM] [varchar](25) NULL,
	[RUC] [varchar](25) NULL,
	[NUM_DOC] [varchar](25) NULL,
	[NOM_AGENTE] [varchar](250) NULL,
	[NOM_EMPRESA] [varchar](250) NULL,
	[DIR_EMPRESA] [varchar](250) NULL,
	[RUC_EMPRESA] [varchar](25) NULL,
	[FEC_INICIO] [varchar](25) NULL,
	[FEC_TERMINO] [varchar](25) NULL,
	[DSCTO_ESTUDIO_C] [varchar](25) NULL,
	[DSCTO_DETRACCION] [varchar](25) NULL,
	[PORC_IGV] [varchar](25) NULL,
	[UNIDAD_NEGOCIO] [varchar](25) NULL,
	[codigo_canal] [varchar](25) NULL,
	[DIMENSION_3] [varchar](25) NULL,
	[DIMENSION_4] [varchar](25) NULL,
	[DIMENSION_5] [varchar](25) NULL
) ON [PRIMARY]
