CREATE TABLE [dbo].[sigeco_reporte_comision_liquidacion] (
    [codigo_planilla]             INT             NULL,
    [fecha_inicio]                VARCHAR (10)    NULL,
    [numero_planilla]             VARCHAR (25)    NULL,
    [fecha_fin]                   VARCHAR (10)    NULL,
    [codigo_tipo_planilla]        INT             NULL,
    [codigo_estado_planilla]      INT             NULL,
    [codigo_empresa]              INT             NULL,
    [nombre_empresa]              VARCHAR (25)    NULL,
    [nombre_empresa_largo]        VARCHAR (250)   NULL,
    [ruc]                         VARCHAR (25)    NULL,
    [direccion_fiscal]            VARCHAR (250)   NULL,
    [codigo_personal]             INT             NULL,
    [nombre_tipo_documento]       VARCHAR (25)    NULL,
    [nombre_personal]             VARCHAR (250)   NULL,
    [nro_documento]               VARCHAR (25)    NULL,
    [email_personal]              VARCHAR (100)   NULL,
    [codigo_personal_referencial] INT             NULL,
    [nombre_personal_referencial] VARCHAR (250)   NULL,
    [email_personal_referencial]  VARCHAR (250)   NULL,
    [nombre_envio_correo]         VARCHAR (250)   NULL,
    [apellido_envio_correo]       VARCHAR (250)   NULL,
    [nro_contrato]                VARCHAR (100)   NULL,
    [nro_cuota]                   INT             NULL,
    [nombre_articulo]             VARCHAR (250)   NULL,
    [nombre_tipo_venta]           VARCHAR (100)   NULL,
    [nombre_tipo_pago]            VARCHAR (100)   NULL,
    [igv]                         DECIMAL (12, 2) NULL,
    [monto_bruto]                 DECIMAL (12, 2) NULL,
    [monto_neto]                  DECIMAL (12, 2) NULL,
    [igv_empresa]                 DECIMAL (12, 2) NULL,
    [bruto_empresa]               DECIMAL (12, 2) NULL,
    [neto_empresa]                DECIMAL (12, 2) NULL,
    [descuento_empresa]           DECIMAL (12, 2) NULL,
    [canal_grupo_nombre]          VARCHAR (250)   NULL,
    [descuento_motivo]            VARCHAR (500)   NULL,
    [codigo_jardines]             VARCHAR (25)    NULL,
    [codigo_moneda]               INT             NULL,
    [detraccion_empresa]          DECIMAL (12, 2) NULL,
    [neto_pagar_empresa]          DECIMAL (12, 2) NULL,
    [neto_pagar_empresa_letra]    VARCHAR (500)   NULL,
    [tipo_reporte]                VARCHAR (25)    NULL,
	codigo_canal                  INT             NULL
);