CREATE TABLE [dbo].[sigeco_reporte_bono_resumen] (
    [codigo_planilla]         INT             NULL,
    [fecha_inicio]            VARCHAR (10)    NULL,
    [fecha_fin]               VARCHAR (10)    NULL,
    [nombre_canal]            VARCHAR (250)   NULL,
    [codigo_estado_planilla]  INT             NULL,
    [codigo_grupo]            INT             NULL,
    [nombre_grupo]            VARCHAR (250)   NULL,
    [codigo_personal]         INT             NULL,
    [nombres_apellidos]       VARCHAR (250)   NULL,
    [codigo_empresa]          INT             NULL,
    [nombre_empresa]          VARCHAR (250)   NULL,
    [monto_bruto_empresa]     DECIMAL (10, 2) NULL,
    [monto_igv_empresa]       DECIMAL (10, 2) NULL,
    [monto_neto_empresa]      DECIMAL (10, 2) NULL,
    [monto_ingresado_empresa] DECIMAL (10, 2) NULL,
    [detraccion_empresa]      DECIMAL (10, 2) NULL,
    [monto_neto_bono_empresa] DECIMAL (10, 2) NULL,
    [monto_bruto_grupo]       DECIMAL (10, 2) NULL,
    [monto_igv_grupo]         DECIMAL (10, 2) NULL,
    [monto_neto_grupo]        DECIMAL (10, 2) NULL,
    [monto_contrato_grupo]    DECIMAL (10, 2) NULL,
    [monto_ingresado_grupo]   DECIMAL (10, 2) NULL,
    [meta_logrado]            DECIMAL (10, 2) NULL,
    [porcentaje_pago]         DECIMAL (10, 2) NULL
);