CREATE TABLE [dbo].[t_comisiones_det_db2] (
    [C_COMISION]    VARCHAR (6)     NOT NULL,
    [D_EMPRESA]     VARCHAR (4)     NOT NULL,
    [D_NIVEL]       VARCHAR (30)    NOT NULL,
    [D_TIPO_AGENTE] VARCHAR (4)     NOT NULL,
    [D_BIEN]        VARCHAR (6)     NOT NULL,
    [D_CONCEPTO]    VARCHAR (3)     NOT NULL,
    [D_IMPORTE_MIN] DECIMAL (10, 3) NULL,
    [D_IMPORTE_MAX] DECIMAL (10, 3) NULL,
    [D_PORCENTAJE]  DECIMAL (10, 3) NULL,
    [FLAG_ACTIVO]   CHAR (1)        NULL,
    [D_COMI_DOLAR]  DECIMAL (10, 2) NULL,
    [S_IMPORTE_MIN] DECIMAL (10, 3) NULL,
    [S_IMPORTE_MAX] DECIMAL (10, 3) NULL,
    [S_PORCENTAJE]  DECIMAL (10, 3) NULL,
    [S_COMI_SOLES]  DECIMAL (10, 3) NULL,
    [C_USUARIO]     VARCHAR (10)    NULL,
    [FEC_REGISTRO]  DATETIME2 (7)   NULL
);