CREATE TABLE [dbo].[venta] (
    [codigo_venta]                   INT             IDENTITY (1, 1) NOT NULL,
    [codigo_persona]                 INT             NOT NULL,
    [codigo_documento]               INT             NULL,
    [numero_documento_cliente]       VARCHAR (15)    NULL,
    [ape_paterno_cliente]            VARCHAR (50)    NULL,
    [ape_materno_cliente]            VARCHAR (50)    NULL,
    [nombre_cliente]                 VARCHAR (50)    NULL,
    [codigo_producto]                INT             NULL,
    [codigo_reserva]                 INT             NOT NULL,
    [estado_registro]                BIT             NOT NULL,
    [numero_contrato]                VARCHAR (60)    NULL,
    [codigo_espacio]                 VARCHAR (20)    NOT NULL,
    [observacion]                    NVARCHAR (200)  NULL,
    [observacion_anulacion]          NVARCHAR (200)  NULL,
    [es_venta_manual]                BIT             DEFAULT ((1)) NOT NULL,
    [precio_venta]                   DECIMAL (20, 8) DEFAULT ((0)) NOT NULL,
    [indica_pago_espacio]            BIT             DEFAULT ((0)) NOT NULL,
    [fecha_registra]                 DATETIME        NOT NULL,
    [fecha_venta]                    DATETIME        NOT NULL,
    [fecha_modifica]                 DATETIME        NULL,
    [usuario_registra]               VARCHAR (50)    NOT NULL,
    [usuario_modifica]               VARCHAR (50)    NULL,
    [motivo_movimiento]              VARCHAR (150)   NULL,
    [codigo_catalogo_bien_contrato]  INT             NOT NULL,
    [codigo_catalogo_bien_espacio]   INT             NOT NULL,
    [codigo_caracteristica_lote]     INT             NOT NULL,
    [codigo_estado_movimiento_tabla] INT             NOT NULL,
    CONSTRAINT [venta_pk] PRIMARY KEY CLUSTERED ([codigo_venta] ASC),
    FOREIGN KEY ([codigo_caracteristica_lote]) REFERENCES [dbo].[caracteristica_lote] ([codigo_caracteristica_lote]),
    FOREIGN KEY ([codigo_catalogo_bien_contrato]) REFERENCES [dbo].[tipo_bien] ([codigo_tipo_bien]),
    FOREIGN KEY ([codigo_catalogo_bien_espacio]) REFERENCES [dbo].[tipo_bien] ([codigo_tipo_bien]),
    CONSTRAINT [cod_estado_mov_tabla_venta_fk] FOREIGN KEY ([codigo_estado_movimiento_tabla]) REFERENCES [dbo].[estado_movimiento_tabla] ([codigo_estado_movimiento_tabla]),
    CONSTRAINT [documento_venta_fk] FOREIGN KEY ([codigo_documento]) REFERENCES [dbo].[documento] ([codigo_documento]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [persona_venta_fk] FOREIGN KEY ([codigo_persona]) REFERENCES [dbo].[persona] ([codigo_persona]),
    CONSTRAINT [producto_venta_fk] FOREIGN KEY ([codigo_producto]) REFERENCES [dbo].[producto] ([codigo_producto])
);