//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Areas.Comision.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_sigeco
    {
        public empresa_sigeco()
        {
            this.cronograma_pago_comision = new HashSet<cronograma_pago_comision>();
            this.empresa_configuracion = new HashSet<empresa_configuracion>();
            this.precio_articulo = new HashSet<precio_articulo>();
        }
    
        public int codigo_empresa { get; set; }
        public string codigo_equivalencia { get; set; }
        public string nombre { get; set; }
        public string nombre_largo { get; set; }
        public string ruc { get; set; }
        public string direccion_fiscal { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public string usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_modifica { get; set; }
        public string nro_cuenta { get; set; }
        public Nullable<int> codigo_cuenta_moneda { get; set; }
        public Nullable<int> codigo_tipo_cuenta { get; set; }
    
        public virtual ICollection<cronograma_pago_comision> cronograma_pago_comision { get; set; }
        public virtual ICollection<empresa_configuracion> empresa_configuracion { get; set; }
        public virtual tipo_cuenta tipo_cuenta { get; set; }
        public virtual ICollection<precio_articulo> precio_articulo { get; set; }
    }
}
