//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Areas.Comision.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_configuracion
    {
        public int codigo_empresa_configuracion { get; set; }
        public int codigo_configuracion { get; set; }
        public int codigo_empresa { get; set; }
        public bool planilla_factura { get; set; }
    
        public virtual configuracion_canal_grupo configuracion_canal_grupo { get; set; }
        public virtual empresa_sigeco empresa_sigeco { get; set; }
    }
}
