//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Areas.Comision.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGECOEntities : DbContext
    {
        public SIGECOEntities()
            : base("name=SIGECOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tipo_cuenta> tipo_cuenta { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<banco> banco { get; set; }
        public virtual DbSet<campo_santo_sigeco> campo_santo_sigeco { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<configuracion_canal_grupo> configuracion_canal_grupo { get; set; }
        public virtual DbSet<empresa_configuracion> empresa_configuracion { get; set; }
        public virtual DbSet<estado_cuota> estado_cuota { get; set; }
        public virtual DbSet<estado_planilla> estado_planilla { get; set; }
        public virtual DbSet<estado_reclamo> estado_reclamo { get; set; }
        public virtual DbSet<estado_resultado> estado_resultado { get; set; }
        public virtual DbSet<moneda> moneda { get; set; }
        public virtual DbSet<personal_canal_grupo> personal_canal_grupo { get; set; }
        public virtual DbSet<regla_calculo_comision> regla_calculo_comision { get; set; }
        public virtual DbSet<tipo_articulo> tipo_articulo { get; set; }
        public virtual DbSet<tipo_comision> tipo_comision { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tipo_pago> tipo_pago { get; set; }
        public virtual DbSet<tipo_planilla> tipo_planilla { get; set; }
        public virtual DbSet<tipo_venta> tipo_venta { get; set; }
        public virtual DbSet<unidad_negocio> unidad_negocio { get; set; }
        public virtual DbSet<canal_grupo> canal_grupo { get; set; }
        public virtual DbSet<precio_articulo> precio_articulo { get; set; }
        public virtual DbSet<cronograma_pago_comision> cronograma_pago_comision { get; set; }
        public virtual DbSet<empresa_sigeco> empresa_sigeco { get; set; }
        public virtual DbSet<personal> personal { get; set; }
    }
}
