//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEES.Web.Areas.Comision.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_cuenta
    {
        public tipo_cuenta()
        {
            this.empresa_sigeco = new HashSet<empresa_sigeco>();
            this.personal = new HashSet<personal>();
        }
    
        public int codigo_tipo_cuenta { get; set; }
        public string codigo_equivalencia { get; set; }
        public string nombre { get; set; }
        public string simbolo { get; set; }
        public bool estado_registro { get; set; }
        public System.DateTime fecha_registra { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_registra { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual ICollection<empresa_sigeco> empresa_sigeco { get; set; }
        public virtual ICollection<personal> personal { get; set; }
    }
}
